projects.json
[PanelKit](https://github.com/louisdh/panelkit) is a UI framework, written in Swift, that utilizes protocols (including extensions) in many ways.
* BSD
* MIT
* MPL 2.0
* CDDL
=> Add PanelKit

projects.json
Guitar adds common string manipulation functions, including common regular expression capabilities, that are needed in both mobile and server-side development, but are missing in Swift's Standard Library.
* BSD
* MIT
* MPL 2.0
* CDDL
=> Added Guitar

projects.json
AsyncNinja project added with builds and tests on macOS, iOS (32bit and 64bit), tvOS.
AsyncNinja strongly relies on a type system with protocol oriented programming and nested generics.
* BSD
* MIT
* MPL 2.0
* CDDL
=> Add AsyncNinja

projects.json
Serpent is a framework made for creating model objects or structs that can be easily serialized and deserialized from/to JSON. It's easily expandable and handles all common data types used when consuming a REST API, as well as recursive parsing of custom objects. 
Through function overloading and generics supports many basic Foundation types, plus platform specific types as `UIColor` and similar. Also uses custom operators heavily.
Due to the Swift source compatibility suite not supporting Carthage yet, this addition does not test the iOS/watchOS/tvOS targets as they contain extensions which have dependencies that are required to be build prior using Carthage.
* BSD
* MIT
* Apache …
=> Add Serpent

projects.json
and passes any unit tests: 3.1
=> Added SRP project

projects.json
[Re-Lax](https://github.com/asynchrony/Re-Lax) is a tvOS framework for generating Parallax images utilizing low level frameworks and APIs such as Accelerate, lzsfe, and unsafe memory access. This is licensed under MIT.
* BSD
* MIT
* MPL 2.0
* CDDL
=> Add Re-Lax

projects.json
SwifterSwift is a collection of over 500 native Swift 3 extensions, with handy methods, syntactic sugar, and performance improvements for wide range of primitive data types, UIKit and Cocoa classes –over 500 in 1– for iOS, macOS, tvOS and watchOS.
* BSD
* MIT
* MPL 2.0
* CDDL
=> Add SwifterSwift

projects.json
as requested in https://github.com/apple/swift-source-compat-suite/pull/3#issuecomment-297223329
=> add a SwiftLint commit to test it on Swift 3.1

projects.json
[Kommander](https://github.com/intelygenz/Kommander-iOS) is a Swift library to manage the task execution in different threads. Through the definition a simple but powerful concept, Kommand.
* BSD
* MIT
* MPL 2.0
* CDDL
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/apple/swift-source-compat-suite/27)
=> Add Kommander

projects.json
[R.swift](https://github.com/mac-cain13/R.swift) is a tool for generating static references to runtime resources in iOS projects. R.swift is used to get strong typed, autocompleted resources like images, fonts and segues in Swift projects.
* BSD
* MIT
* MPL 2.0
* CDDL
=> Add R.swift

projects.json
=> Add Dwifft

projects.json
=> Add Result

build_incremental.py, project.py, projects-incremental.json
Add an incremental testing mode (that tests fragments of a project's git history), as well as machinery for collecting and enforcing limits on compiler-emitted statistics.
=> Incremental mode

projects.json
Add XFAIL for projects with Sequence.Element clashes while issue is being resolved.
=> XFAIL projects with Sequence.Element clashes

projects.json
Goes with https://github.com/apple/swift/pull/9847
=> Un-XFAIL Vapor

projects.json
=> add CoreStore

projects.json
LaunchScreenSnapshot protects sensitive data in your app snapshot.
* BSD
* MIT
* MPL 2.0
* CDDL
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/apple/swift-source-compat-suite/44)
=> Add LaunchScreenSnapshot

build_incremental.py, project.py, projects-incremental.json
Three changes (recently discussed):
- Add some new incremental test sequences to the incremental projects file
- Remove everything stats-related from the scripts
- Add support for added_swift_flags to the swiftpm actions
=> Stats and incremental cleanups

projects.json
Chatto is a Swift lightweight framework to build chat applications. It uses full power of Swift language to be performant and extensible. MIT license
* BSD
* MIT
* MPL 2.0
* CDDL
=> Chatto 3.1.0

projects.json
Added CleanroomLogger to `projects.json`
=> added CleanroomLogger project

.gitignore, projects.json
This adds my project, [JSQDataSourcesKit](https://github.com/jessesquires/JSQDataSourcesKit).
**NOTE:** This project has revealed a regression in Swift 4. See: [SR-4088](https://bugs.swift.org/browse/SR-4088).
* BSD
* MIT
* MPL 2.0
* CDDL
=> [Add Project] JSQDataSourcesKit

projects.json
This reverts commit 3dfea803c1f0387740505824b01a8d2ea5a1625d.
=> Un-XFAIL vapor, Kitura.

projects.json
It is UPASS'ing at https://ci.swift.org/job/swift-PR-source-compat-suite/359/artifact/swift-source-compat-suite/
See also https://bugs.swift.org/browse/SR-5500
=> Un-XFAIL ChattoApp

projects.json
=> UnXFAIL GRDB. SR-5235.

run_cperf
This fixes a bunch of miscellaneous problems with the run_cperf script, either in terms of running wrong or generating sub-optimal output.
=> Cperf tuning

projects.json
See https://bugs.swift.org/browse/SR-5998 for description of the problem.
=> XFAIL AsyncNinja

run_cperf
Attempting to debug the run_cperf script.
=> [run_cperf] Add debugging output and adjust stats dirs

run_cperf
Another round of debugging, aiming for either fixing the nondeterminism or revealing its source.
=> [run_cperf] More debugging experiments.

projects.json
Updated Guitar's commit hash and version as it now supports Swift 4.0.
- [ x be contained in a publicly accessible git repository
* BSD
* MIT
* MPL 2.0
* CDDL
=> Updated Guitar for Swift 4.0

run_cperf
Hopefully nearing the end of silly fixes.
=> [run_cperf] Fix typo.

run_cperf
Another iteration of fixes to run_cperf.
=> Cperf fixes oct 3

projects.json
=> XFAIL Kitura; it's (indirectly) referencing underscored protocols.

projects.json
Previous commit was a little off
=> Stray comma in previous xfail commit

.github/PULL_REQUEST_TEMPLATE.md
Done in #90 but not updated here.
=> Update PULL_REQUEST_TEMPLATE.md for check script rename

projects.json
=> XFAIL JSQDataSourcesKit

projects.json
This reverts commit f8fcc8942fdde543c9b60a4b9589a175aebd9e99.
rdar://35729528
SR-6484
=> Revert "XFAIL JSQDataSourcesKit"

projects.json
SR-6488
rdar://problem/35740248
=> XFAIL Plank and R

projects.json
=> UNXFAIL fixed SwiftLint SR-6349

projects.json
Resolve ProcedureKit XFAIL by advancing project hash.
=> Resolve ProcedureKit XFAIL

projects.json
rdar://35633455 has been resolved.
=> Un-XFAIL SwiftLint project

projects.json
Resolve Surge XFAIL by advancing to a project hash that resolves rdar://problem/32185310 (invalid Element redeclaration).
=> Resolve Surge XFAIL

projects.json
Resolve Kitura XFAIL by advancing its project hash.
=> Resolve Kitura XFAIL

projects.json
Resolve Realm XFAIL by advancing project hash to a version containing a fix for SR-4730.
=> Resolve Realm XFAIL

projects.json
Hello, this pull request adds a commit for GRDB.swift and Swift 4.0
> - [ ] pass `./project_precommit_check` script run
The output of the command is undecipherable:
> ```
> usage: project_precommit_check [-h] --earliest-compatible-swift-version
>                                VERSION [--swiftc PATH]
>                                project
> project_precommit_check: error: too few arguments
> ```
I could never make it work.
=> GRDB.swift and Swift 4

projects.json
see apple/swift#14299 & apple/swift-source-compat-suite#129 for motivation
Should supersede #129.
=> Update SwiftLint commits for IUO change

project_future.py, runner.py
This PR adds a new flag for setting additional xcodebuild flags.
=> Add support for adding additional xcodebuild flags at runner invocation

projects.json
Adds 4.0 commits for `AMScrollingNavbar`
* BSD
* MIT
* MPL 2.0
* CDDL
=> Add Swift 4 commit for AMScrollingNavbar

project_future.py
This PR removes the concept of "version" from the abstract class ActionBuilder.
=> Make a few misc. improvements

projects.json
Update BeaconKit compatibility versions to include 4.0 and 4.0.3.
- [✅] be an *Xcode* or *swift package manager* project
- [✅] support building on either Linux or macOS
- [✅] target Linux, macOS, or iOS/tvOS/watchOS device
- [✅] be contained in a publicly accessible git repository
- [✅] maintain a project branch that builds against Swift 3.0 compatibility mode
- [✅] have maintainers who will commit to resolve issues in a timely manner
- [✅] be compatible with the latest GM/Beta versions of *Xcode* and *swiftpm*
- [✅] add value not already included in the suite
- [✅] be licensed with one of the following permissive licenses:
* BSD
* MIT
* Eclipse Public …
=> Update BeaconKit compatibility versions to include 4.0 and 4.0.3

projects.json
=> Adding 4.0 compatibility to AsyncNinja

projects.json
This is in response to the request for each project maintainer add a new project hash that’s configured to build in Swift 4.0 compatibility mode.
- [ x ] be an *Xcode* or *swift package manager* project
- [ x ] support building on either Linux or macOS
- [ x ] target Linux, macOS, or iOS/tvOS/watchOS device
- [ x ] be contained in a publicly accessible git repository
- [ x ] maintain a project branch that builds against Swift 3.0 compatibility mode
- [ x ] have maintainers who will commit to resolve issues in a timely manner
- [ x] add value not already included in the suite
- [ x] be licensed with one of the following permissive licenses:
* BSD
* MIT
* …
=> Update Plank source compatability to include Swift 4.0.3

projects.json
Adds Swift 4 compatibility SHA to Re-Lax
* BSD
* MIT
* MPL 2.0
* CDDL
=> Add Swift 4 compatibility to Re-Lax

projects.json
Add Swift 4.0 compatibility commit to SwifterSwift
* BSD
* MIT
* MPL 2.0
* CDDL
=> Add 4.0 compatibility to SwifterSwift

projects.json
[Cub](https://github.com/louisdh/cub) is an interpreted scripting language inspired by Swift. This project includes a lexer, parser, compiler and interpreter. All of these are 100% written in Swift without dependencies.
**Cub does not support Swift 3.0, but I'm guessing the pull request template may be updated to say "Swift 4.0"?**
* BSD
* MIT
* MPL 2.0
* CDDL
=> Add the Cub programming language

run_cperf
A grab bag of adjustments to try to make run_cperf more usable / less fail-y. Lately it's been unusable.
=> Misc cperf tweaks

projects.json
Updating config for Dollar project as it works with Swift 4
* BSD
* MIT
* MPL 2.0
* CDDL
=> Adding config for Swift 4 support

projects.json
https://github.com/apple/swift/pull/15856 fixes this.
=> un-XFAIL RxSwift.

projects.json
Fixes master hash to resolve 4.2 issues
* BSD
* MIT
* MPL 2.0
* CDDL
=> Updates Sourcery hash for conformance changes

projects.json
Hello, this pull requests extends GRDB with Swift 4.1
* BSD
* MIT
* MPL 2.0
* CDDL
=> Add GRDB + Swift 4.1

projects.json
- Update hash for 4.0 mode to latest version of AMScrollingNavbar
- Drop testing of 3.0 mode for this project.
=> Update hash for AMScrollingNavbar to tip of trunk, and drop 3.0 mode.

projects.json
- Update to use latest version of Kronos project.
- Project is already configured to use 4.0
- Drop building project in 3.0
=> Update hash so that Kronos builds with Swift 4

projects.json
- Drop building SwifterSwift in 3.0 mode
- Update to tip-of-master for building SwifterSwift in 4.0 mode.
=> Drop building SwifterSwift in 3.0 mode.

projects.json
https://github.com/apple/swift-nio
```
./project_precommit_check swift-nio --earliest-compatible-swift-version 4.2
** CHECK **
--- Validating swift-nio Swift version 4.2 compatibility ---
--- Checking swift-nio platform compatibility with Darwin ---
$ /Applications/Xcodes/Xcode-10-beta-3.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc --version
$ ./runner.py --swift-branch swift-4.2-branch …
```
=> Add SwiftNIO

projects.json
Problem described in https://bugs.swift.org/browse/SR-8403 has been resolved.
=> un-XFAIL SwiftNIO project

project_precommit_check
...to the version included in Xcode 10 Beta 5.
=> Update project_precommit_check's 4.2 swiftlang version

sourcekit-xfails.json
Also update the file offsets for the PinkyPromise xfail following a recent hash update.
=> Update sourcekit-xfails.json for master

projects.json
Updates the Deferred project hash to a recent commit, and the config to build against Swift 4.2. Also removes the 4.0 xfail for [SR-8234](https://bugs.swift.org/browse/SR-8234)
```
./project_precommit_check Deferred --earliest-compatible-swift-version 4.2
** CHECK **
--- Validating Deferred Swift version 4.2 compatibility ---
--- Checking Deferred platform compatibility with Darwin ---
$ ./runner.py …
```
=> Update Deferred hash to build against 4.2

projects.json
Adds the [SwiftyJSON](https://github.com/SwiftyJSON/SwiftyJSON) project to the suite.
* MIT
```
$ ./project_precommit_check SwiftyJSON --earliest-compatible-swift-version 4.2
** CHECK **
--- Validating SwiftyJSON Swift version 4.2 compatibility ---
--- Checking SwiftyJSON platform compatibility with Darwin ---
$ ./runner.py …
```
=> Add SwiftyJSON

projects.json
This fixes an issue that resulted in the project getting xfailed.
=> fix BeaconKit and remove xfail

projects.json
Update BlueSocket commit and config to build against Swift 4.2
```
PASS: BlueSocket, 4.2, fb4e74, Socket, generic/platform=macOS
PASS: BlueSocket, 4.2, fb4e74, Socket-iOS, generic/platform=iOS
Passed: 2
Failed: 0
XFailed: 0
UPassed: 0
Total: 2
Total: 1
Result: PASS
```
=> Update BlueSocket commit and config to build against Swift 4.2

projects.json
Updates the hash of KeychainAccess to build against Swift 4.2.
```
PASS: KeychainAccess, 4.2, 0fffcc, KeychainAccess, platform=macOS
PASS: KeychainAccess, 4.2, 0fffcc, KeychainAccess, generic/platform=iOS
PASS: KeychainAccess, 4.2, 0fffcc, KeychainAccess, generic/platform=tvOS
PASS: KeychainAccess, 4.2, 0fffcc, KeychainAccess, generic/platform=watchOS
Passed: 4
Failed: 0
XFailed: 0
UPassed: 0
Total: 4
Total: 1
Result: PASS
```
=> Update KeychainAccess hash to build against 4.2

projects.json
This adds https://github.com/pointfreeco/swift-html.
* BSD
* MIT 👈
* MPL 2.0
* CDDL
=> Add swift-html

projects.json
This reverts commit e6da890d3e9bdf86405f853f80e398e5dc9531bc.
=> Revert "XFAIL IBAnimatable: SR-9146"

projects.json
https://bugs.swift.org/browse/SR-9252
=> XFAIL Tagged on swift-5.0-branch

projects.json
This was resolved by https://github.com/apple/swift/pull/20927.
=> Un-XFAIL ModelAssistant since it now works.

projects.json
```
PASS: AMScrollingNavbar, 4.2, 8bfcc8, AMScrollingNavbar, generic/platform=iOS
```
Tested with Xcode 10.1
=> [4.2] Update AMScrollingNavbar to support Swift 4.2

projects.json
It's currently UPASSing on master: https://ci.swift.org/job/swift-master-source-compat-suite/3015
=> Remove line-sdk-ios-swift xfail

checkout, project.py, project_future.py
We lost a function def somehow. Add it back, and fix call to match.
=> Fix checkout script

projects.json
Fixed by https://github.com/apple/swift/pull/22074
=> Un-XFAIL vapor/routing

project_future.py
Also add `clean_build` flag to control if xcode `build` command
should delete previous build information.
=> Add an ability to control environment per build action

projects.json
Add a Swift 4.2 check for SwiftGraph
=> Add SwiftGraph for Swift 4.2

projects.json
Lark is no longer failing.
Fixes rdar://49367012
=> Un-XFAIL Lark

projects.json
Add new 5.0 configuration for SwiftDate.
=> Add 5.0 configuration for SwiftDate

sourcekit-xfails.json
=> Remove apparently fixed Dollar SourceKit XFAIL

run_sk_stress_test, sourcekit-xfails.json
Also try to fix the encoding failure the bots are hitting.
=> [run_sk_stress_test] Update xfails for master

projects.json
=> XFail SwifterSwift

projects.json
=> Re-enable SwifterSwift-watchOS since it's no longer failing

projects.json
https://bugs.swift.org/browse/SR-11135
https://bugs.swift.org/browse/SR-11136
=> XFail R.swift and RxDataSources

project_precommit_check
...to match swiftlang that shipped with Xcode 11 beta 4.
=> Update project_precommit_check 5.1 configuration

projects.json
Add all the projects of the SwiftNIO family that are mostly pure Swift.
=> SwiftNIO family: update & add missing

projects.json, run_sk_stress_test, sourcekit-xfails.json
=> [run_sk_stress_test] Add Base64CoderSwiftUI to the set of smoke test projects and update xfails

projects.json
- [💚] be an *Xcode* or *swift package manager* project
- [💚] support building on either Linux or macOS
- [💚] target Linux, macOS, or iOS/tvOS/watchOS device
- [💚] be contained in a publicly accessible git repository
- [💚] maintain a project branch that builds against Swift 5.0 and passes any unit tests
- [💚] have maintainers who will commit to resolve issues in a timely manner
- [💚] be compatible with the latest GM/Beta versions of *Xcode* and *swiftpm*
- [💚] add value not already included in the suite
- [💚] be licensed with one of the following permissive licenses:
* MIT
- [💚] pass …
=> add RxReactiveObjC

projects.json
https://bugs.swift.org/browse/SR-11350
=> [XFail] Base64CoderSwiftUI due to assertion failure

projects.json
This PR adds Bow to the list of projects. [Bow](https://bow-swift.io/) is a library for Typed Functional Programming in Swift. 
* BSD
* MIT
* MPL 2.0
* CDDL
=> Add project Bow

projects.json
=> XFAIL starscream 5.1

projects.json
This will resolve the upass in CI.
=> Remove swift-5.1-branch from xfail configuration

projects.json
Updating for a request made offline to handle a possible future compiler ambiguity. See bignerdranch/Deferred#295.
=> Update 5.1 hash for Deferred

sourcekit-xfails.json
Resolves rdar://problem/58533499
=> [run_sk_stress_test] Update xfails after SR-11911 was fixed

projects.json
=> Remove Sourcery xfail

runner.py
To track investigation: <rdar://problem/59302454>.
To track that we actually fix: <rdar://problem/59302467>.
=> Disable dsym generation (but keep generating debug info) until old dsymutil compatibility issue is addressed.

projects.json
rdar://56059920
https://bugs.swift.org/browse/SR-11587
c.f. https://ci.swift.org/job/swift-master-source-compat-suite//4623/console
=> Un-XFAIL Starscream

projects.json
https://bugs.swift.org/browse/SR-12322
=> xfail starscream on swift-5.2-branch

projects.json
The overload resolution broke recently on master (SR-12291).  Add this
to the test suite for future testing.
* BSD
* MIT
* MPL 2.0
* CDDL
=> Add Nimble to the test suite

sourcekit-xfails.json
https://ci.swift.org/job/swift-master-sourcekitd-stress-tester/2176/consoleText
=> [run_sk_stress_test] Updates xfails

projects.json
More SwiftUI code in both apps.
=> Update MovieSwiftUI & ACHNBrowserUI to latest commits

projects.json
https://bugs.swift.org/browse/SR-11141
=> XFAIL RxCocoa on release/5.3

projects.json
This is only applicable to `Debug` configuration.
=> XFAIL Kickstarter and ReactiveSwift targets affected by SR-13548

README.md, common.py, project.py, project_future.py, projects.json, reproduce.py
=> Update the scripts to use main branch

projects.json
https://bugs.swift.org/browse/SR-13592
```
/Users/buildnode/Library/Developer/Xcode/DerivedData/ACHNBrowserUI-eprjuawgxdjegffqxjrlvidczecq/SourcePackages/checkouts/purchases-ios/Purchases/Public/RCPurchasesErrorUtils.m:201:18: error: use of undeclared identifier 'SKErrorIneligibleForOffer'
case SKErrorIneligibleForOffer:
^
1 error generated.
```
=> Xfail ACHNBrowserUI

projects.json
https://bugs.swift.org/browse/SR-13623
=> Xfail siesta and siesta-legacy

projects.json
Reverts apple/swift-source-compat-suite#458
=> Revert "Xfail ACHNBrowserUI"

projects.json
All of them are currently UPASS'ing in release and debug configurations.
=> Un-XFAIL projects previously failing due to SR-13189

projects.json
Add https://github.com/apple/swift-algorithms
```
PASS: swift-algorithms, 5.2, 386460, Swift Package
Passed: 1
Failed: 0
XFailed: 0
UPassed: 0
Total: 1
Total: 1
Result: PASS
--- swift-algorithms checked successfully against Swift 5.2 ---
```
=> Add swift-algorithms

projects.json
Just updating/adding some SwiftNIO family projects & Swift Crypto
.
=> update/add SwiftNIO family projects + Swift Crypto

projects.json
https://bugs.swift.org/browse/SR-14090
=> Xfail swift-futures

projects.json
Reverts apple/swift-source-compat-suite#486
Fixed - https://github.com/apple/swift/pull/35596
=> Revert "Xfail swift-futures"

projects.json
Add grpc-swift
- 5.2+
- Apache License, version 2.0
```
Passed: 1
Failed: 0
XFailed: 0
UPassed: 0
Total: 1
Total: 1
Result: PASS
--- grpc-swift checked successfully against Swift 5.2 ---
```
=> Add grpc-swift

runner.py
=> Avoid using the new driver to run the source compatiblity test suite

project_future.py
Reverts apple/swift-source-compat-suite#513
=> Revert "Add disable-incremental-imports flag to workaround debug failure"

projects.json
Addresses Mishal's comment here: https://github.com/apple/swift-source-compat-suite/pull/518#discussion_r611820698
=> Update the BeaconKit XFAIL issue link to one on bugs.swift.org.

projects.json
Reverts apple/swift-source-compat-suite#519
=> Revert "Update the BeaconKit XFAIL issue link to one on bugs.swift.org."

projects.json
Reverts apple/swift-source-compat-suite#518
=> Revert "XFAIL BeaconKit"

sourcekit-xfails.json
SR-14431 have been duped, SR-12985, SR-12965, SR-14432, SR-14455 have been fixed.
=> [Stress Tester XFails] Rename SR-14431 to SR-8898 and remove SR-12985

sourcekit-xfails.json
=> [Stress Tester XFAils] Remove SR-14454

sourcekit-xfails.json
=> [Stress Tester XFails] Remove SR-12973, SR-14495, SR-14497

sourcekit-xfails.json
=> [Stress Tester XFails] Remove SR-14494 and apple/swift#36943

projects.json
https://bugs.swift.org/browse/SR-14655
=> XFAIL RxTest for SR-14655

projects.json
It failed in CI: https://bugs.swift.org/browse/SR-14659
=> XFAIL "Doggie" on 5.4

sourcekit-xfails.json
=> [Stress Tester XFails] Update XFails

projects.json
=> XFAIL projects for Collection.subscript(_:) change

projects.json
This project is currently failing in the source compatibility suite
https://bugs.swift.org/browse/SR-15060
https://ci.swift.org/job/swift-main-source-compat-suite//6056/console
https://ci.swift.org/job/swift-main-source-compat-suite-debug//4168/console
=> XFAIL swift-distributed-tracing

projects.json
See https://bugs.swift.org/browse/SR-15146 and https://bugs.swift.org/browse/SR-15145
=> XFAIL some failing compat tests

projects.json
=> Update version of Doggie

common.py
=> update swift-system to 1.1.0

common.py
=> update swift-system to 1.1.1

projects.json
=> Update the AsyncNinja 5.0 sha

projects.json
Project switch to use `main` instead of `master` - https://github.com/MobileNativeFoundation/Kronos
=> Switch Kronos' branch to main

cleanup, common.py
This mirrors the tag on apple/swift main.
=> Add support for apple/swift-experimental-string-processing

common.py
=> Update string processing tag to dev/8.

projects.json
Kingfisher fails on a new parsing error on an SDK's swiftinterface.
rdar://94154905
=> XFail Kingfisher on watchOS and tvOS

projects.json
rdar://94154905 was resolved by https://github.com/apple/swift/pull/59235.
=> Un-XFail Kingfisher

projects.json
To unblock PR source-compat testing.
rdar://96437311
=> [xfail] swift-numerics

CODEOWNERS
Add myself to the codeowners file
cc @shahmishal
=> Add myself to the codeowners

projects.json
* The building environment has been updated so `MovieSwift` and `ACHNBrowserUI` should now pass
=> Remove xfails for  https://github.com/apple/swift/issues/57442

projects.json
Updated fail to match compiler change.
=> Removed xfail.

projects.json
This is paired up with https://github.com/apple/llvm-project/pull/5183 / https://github.com/apple/swift/pull/60733
=> remove XFAILS for 60577

projects.json
Swift compiler is crashing when attempting to build Doggie on Linux
https://github.com/apple/swift/issues/60877
This issue only affects release builds of the project
=> Xfail Doggie on Linux 

projects.json
Xfail project after recent package manager changes
=> Xfail swift-protobuf-plugin-example on main

projects.json
Xfail corestore per https://github.com/apple/swift/issues/61905
=> Xfail CoresStore https://github.com/apple/swift/issues/61905

common.py
Reverts apple/swift-source-compat-suite#737
=> Revert "common.py: update ArgumentParser to 1.2.0"

projects.json
Update some xfails specific to linux after #725 
https://ci.swift.org/job/swift-source-compat-suite-ubuntu-2004/
=> Update xfails for linux after test builds enabled

projects.json
Xfail  Rxswift https://github.com/apple/swift/issues/63242
=> Xfail rxswift https://github.com/apple/swift/issues/63242

sourcekit-xfails.json
Added expected failures for https://github.com/apple/swift/issues/63374 in addition to a handful of timeouts.
=> Update SourceKit XFails

sourcekit-xfails.json
Update for https://github.com/apple/swift/pull/63378
=> [5.8] Update SourceKit XFails for if/switch expressions

common.py
see https://github.com/apple/swift/pull/63521
=> update argument parser to 1.2.2

sourcekit-xfails.json
Reverts apple/swift-source-compat-suite#765
=> Revert "[5.8] Update SourceKit XFails for if/switch expressions"

projects.json
=> Update the swift-nio to 2.48.0 tag

project.py, projects.json
* Build tests only when building the debug config
* Xfail recent linux failures
=> Build tests in debug mode only

projects.json
=> xfail Doggie https://github.com/apple/swift/issues/64319

projects.json
Doggie was fixed with https://github.com/apple/swift/commit/0a4b0a8da764d8bc09625f093e4151b58e5e890e
=> Remove doggie xfail

projects.json
In This PR
* Update various projects with xfails and created the associated git issues
=> Update various xfails after 14.2 deployment

project.py, projects.json
* Add the ability to prioritize project builds first in order to prevent other breakages
=> add ability to build projects first as a priortity

projects.json
* Add swift-testing to the source compat suite
=> Add swift-testing

projects.json
* Update the xfails file for swift-testing. 
Filed:
* https://github.com/apple/swift/issues/69278
* https://github.com/apple/swift/issues/69279
=> Update xfails for swift-testing

projects.json
* Update the xfails file after https://github.com/apple/swift/pull/69163
=> update xfails after rebranch merge

projects.json
Project was updated recently to fix incorrect syntax that was previously accepted by the compiler.
=> Update CareKit project

projects.json
* Update the xfails recently added by #858
=> update carekit xfail

projects.json
* Update carekit to contain source fix: https://github.com/carekit-apple/CareKit/commit/5288dce002c38d81ee6470fc7dbe41f5d80de375
* Remove xfails after https://github.com/apple/swift/issues/70072 was fixed
=> Bump carekit version

project.py, projects.json
Update the source compat suite in preparation of the update to Xcode 15.2. This includes:
* Update deployment targets
* Fix bug with altering environment variables across builds
* Update swift-collections to a newer revision which accommodates the xcode version
* Update xfails
Newly discovered/created issues:
* https://github.com/apple/swift/issues/70744
* https://github.com/apple/swift/issues/70742
=> Xcode 15 update

projects.json
=> update doggie xfail

projects.json
Add Xfail for: https://github.com/apple/swift/issues/70970
=> xfail Result (https://github.com/apple/swift/issues/70970)

projects.json
https://github.com/apple/swift/issues/71423
=> Add xfail  for penny-bot on main (https://github.com/apple/swift/issues/71423)

projects.json
https://github.com/apple/swift/issues/70970
=> "Result" project is passing now

projects.json
This should fix a recent test suite regression with this package.
=> Update `swift-testing` to 0.5.1 in `projects.json`

projects.json
This issue was recently reported in https://github.com/apple/swift/issues/72133 and previously in https://github.com/apple/swift/issues/57554.
=> XFail RxReactiveObjC on main

projects.json
rdar://123970205
rdar://124167314
=> XFail swift-foundation and swift-sdk-generator in some configurations

projects.json
Update xfails with recent failures
=> update xfails for main, 6.0, and 5.9

projects.json
=> Remove xfail on penny-bot

projects.json
=> Xfail swift-distributed-actors.

projects.json
=> Re-enable swift-distributed-actors for release/6.0

projects.json
This issue was not resolved and has been re-reported now.
We must fix it before 6.0 ships, radar here: rdar://127206143
=> xfail distributed actor cluster until fixed

projects.json
Updates Vapor's packages to remove archived packages, fix for renames and add new packages
=> Update Vapor packages

projects.json
This reverts commit 09e128f80386a4806a428367b452ae3163c4fea5.
=> Test the Result project in the SourceKit stress tester again

sourcekit-xfails.json
Remove XFAILs that are no longer failing
=> Update stress tester XFAILs

projects.json
https://github.com/swiftlang/swift-corelibs-foundation/issues/5108
=> [6.1] Xfail RxSwift

projects.json
follow up from 
https://github.com/swiftlang/swift-source-compat-suite/pull/966
https://github.com/swiftlang/swift-package-manager/issues/8292
=> Penny-Bot xfail

projects.json
Unxfail violet, it is passing now
=> Unxfail violet

projects.json
=> unxfail kingfisher and reactiveswift

projects.json
Filed issue and xfailed associated projects
=> xfail projects

projects.json
https://github.com/swiftlang/swift/issues/79888
=> XFail GRDB

projects.json
=> Update the projects.json to include xfails for release/6.2

projects.json
https://github.com/swiftlang/swift/issues/80935
=> XFAIL Alamofire and kommander projects on main due to verifier crash

projects.json
Reverts swiftlang/swift-source-compat-suite#999
=> Revert "XFAIL Alamofire and kommander projects on main due to verifier crash"

projects.json
Projects: Kickstarter-ReactiveExtensions, Moya, Reactive{Cocoa, Swift}
=> XFAIL projects affected by SE-0481

projects.json
Adds Swift OpenAPI Runtime and Swift OpenAPI Generator.
=> Add Swift OpenAPI packages

projects.json
Bump the async-http-client project revision
=> [async-http-client] bump project revision

projects.json
follow up to https://github.com/swiftlang/swift-source-compat-suite/pull/1018
=> Xfail siesta - debug
