- README.md
The `platforms` field seems to be required for all projects in `projects.json` (see the error I got when it wasn't set below). The readme examples didn't contain it oddly enough. I've added it with `Darwin` as an example value.
Error received:
```
Traceback (most recent call last):
File "./check", line 153, in <module>
sys.exit(main())
File "./check", line 147, in main
compatibility_version = get_project_compatibility(args.project)
File "./check", line 84, in get_project_compatibility
if not platform.system() in project['platforms']:
KeyError: 'platforms'
```
> Add "platforms" field to readme examples

- projects.json
[SwiftLint](https://github.com/realm/SwiftLint) is a linter & formatter, used to enforce Swift style and usage conventions.
* BSD
* MIT
* MPL 2.0
* CDDL
> Add SwiftLint

- projects.json
PinkyPromise is an almost-Promises library used to build composable, repeatable, failable asynchronous tasks in functional style. It has thorough tests, documentation, and a teaching playground. It's distributable by source, CocoaPods, Carthage, and the Swift Package Manager.
This library includes a lot of generics, tuples, throwing, and function parameters/properties. Uses of PinkyPromise tend to include chained generic closure expressions that strain type inference. If there is a project in the suite that covers the same territory already, it's likely to be RxSwift. Let that be your litmus test.
PinkyPromise has no dependencies besides basic Foundation, so should work on Linux. But my Vagrant-fu is shallow, and I haven't been able to verify. I've only included Darwin for now.
To be …
> Add PinkyPromise

- projects.json
SwiftGraph is a graph data structure and related algorithms. It wasn't clear to me from the README if you're yet accepting 3.1 pull requests because it said the 3.0s were "examples." Specifically, I mean this section:
```
After adding a new project to the index, ensure it builds successfully at the pinned commits against the specified versions of Swift. In the examples, the commits are specified as being compatible with Swift 3.0, which is included in Xcode 8.0.
```
* BSD
* MIT
* MPL 2.0
* CDDL
> Add SwiftGraph Against Swift 3.1

- projects.json
Hello, this PR adds source compatibility tests for [GRDB.swift](http://github.com/groue/GRDB.swift), a toolkit for SQLite databases, focused on application development.
GRDB requires Xcode 8.1+, and won't build with the toolchain included in Xcode 8.0 (compiler crash). This is why the checked Swift version is 3.1.
GRDB was born in June 2015, has evolved from Swift 2.1 to Swift 3.1, and has a very low number of open issues. It enjoys a small community of involved users that help enhancing a robust and well-appreciated library.
GRDB is a protocol-oriented database library which uses a great deal of Swift features: availability checks, fixits, fine-grained access control, interactions with C and Foundation, and dependency on a [system …
> Add GRDB.swift

- projects.json
This project also builds on 3.0.2, but I don't have Xcode 8.0 hanging around. I verified it against 3.0.2-RELEASE, but the build scripts only accept Xcode's version of Swift 3.0.2.
> Add Lark project

- projects.json
This project also builds on 3.0.2, but I don't have Xcode 8.0 hanging around. I verified it against 3.0.2-RELEASE, but the build scripts only accept Xcode's version of Swift 3.0.2.
> Add DNS project

- projects.json
Kronos is an NTP client library written in Swift. It supports sub-seconds
precision and provides an stable monotonic clock that won't be affected by clock
changes.
* BSD
* MIT
* MPL 2.0
* CDDL
> Add Kronos

- projects.json
Mapper is a simple Swift library to convert JSON to strongly typed objects. One
advantage to Mapper over some other libraries is you can have immutable
properties.
* BSD
* MIT
* MPL 2.0
* CDDL
> Add Mapper

- project.py
according to a comment from Slava Pestov in [SR-4731](https://bugs.swift.org/browse/SR-4731)
> we should make it a policy that projects in the source compat suite should not build with errors as warnings enabled.
Rather than force projects to abide by this condition, simply disable "treat warnings as errors" when invoking `xcodebuild`.
I wasn't able to fully validate this was working so please confirm before merging /cc @lplarson.
> disable "treat warnings as errors" when running xcodebuild

- projects.json
Added NetService project. It builds and tests against 3.1, but on Linux it doesn't against 3.1.1 [SR-4754](https://bugs.swift.org/browse/SR-4754).
* BSD
* MIT
* MPL 2.0
* CDDL
> Added NetService project

- projects.json
[ProcedureKit](https://github.com/ProcedureKit) is a cross platform framework which provides advanced (`NS`)`Operation` functionality.
I think this project adds value to the suite, as it has been actively maintained since Swift 1.0, is (relatively) widely used, it requires compatibility with a range of key upstream frameworks such as Dispatch and CloudKit, and utilises a number of Swift language features such as availability, protocol orientated design with default implementation and generics.
> Adds ProcedureKit

- projects.json
Update previously added AsyncNinja:
- build actions were added for watchOS and swift package manager
- revision was updated
- swift version changed from 3.0 to 3.1
* BSD
* MIT
* MPL 2.0
* CDDL
> Updated AsyncNinja: latest version and more platforms

- projects.json
Adds RxSwift to the project index
* BSD
* MIT
* MPL 2.0
* CDDL
> adds RxSwift to project index

- project.py
- projects.json
So far most projects were built in Debug configuration, although "Release" is specified in projects.json.
Now all the projects are really compiled in Release configurations.
This exposes a bug in AsyncNinja, therefore this PR also xfails this project
> Set the build configuration for xcode-build correctly.  

- projects.json
It passes now because generic inlining is disabled
> un-xfail AsyncNinja

- projects.json
KeychainAccess is a simple Swift wrapper for Keychain API that works on iOS, watchOS, tvOS and macOS. KeychainAccess framework being added here is licensed under MIT.
* BSD
* MIT
* MPL 2.0
* CDDL
> add KeychainAccess

- projects.json
Thanks to @airspeedswift for his help on resolving the issue. I've renamed the `Element` type to `SchemaElement`, which resolves the issue with Swift 4's swift-3-mode.
> `Element` name clash was resolved in Lark

- projects.json
This [AsyncNinja](https://github.com/AsyncNinja/AsyncNinja) update fixes crashes and warnings that were found during testing with latest Swift 4.0 toolchain.
* BSD
* MIT
* MPL 2.0
* CDDL
> AsyncNinja project updated

- projects.json
Adding [URBNJSONDecodable](https://github.com/urbn/URBNJSONDecodable) to the Swift Source Compatibility Suite.
@swift-ci Please test source compatibility
> Submitting URBNJSONDecodable

- build_incremental.py
- builder.py
- project.py
- runner.py
Adding the --build-config option which gives the ability to either build with the debug or release configuration.   Capitalization is adjusted to accommodate a Swift package or an Xcode project as an implementation detail.
> Adding the --build-config option

- projects.json
<rdar://problem/33875468>
[SR-5683]: source-compat-suite failure: mapper
> XFAIL mapper due to warning-as-errors

- projects.json
As the 'charactes deprecated' warning does not exist there.
> UnXFAIL mapper for swift-4.0-branch

- projects.json
Add the latest Swift 3.1 release of ReactiveSwift and ReactiveCocoa to the suite.
Note: These releases build with only Swift 3.1 though. Not quite sure if the suite accepts only 3.1 builds that are source compatible with 3.0.
* MIT
> Update the ReactiveSwift and ReactiveCocoa entries.

- projects.json
This PR adds BeaconKit to the Swift compatibility suite.
The specified commit also builds and passes under the latest 4.0 compiler, both in 3.2 and 4.0 modes.
- [✅] be an *Xcode* or *swift package manager* project
- [✅] support building on either Linux or macOS
- [✅] target Linux, macOS, or iOS/tvOS/watchOS device
- [✅] be contained in a publicly accessible git repository
- [✅] maintain a project branch that builds against Swift 3.0 compatibility mode
- [✅] have maintainers who will commit to resolve issues in a timely manner
- [✅] be compatible with the latest GM/Beta versions of *Xcode* and *swiftpm*
- [✅] add value not already included in the suite
- [✅] be licensed with one of the …
> added BeaconKit

- projects.json
This adds my project, [JSQCoreDataKit](https://github.com/jessesquires/JSQCoreDataKit).
* BSD
* MIT
* MPL 2.0
* CDDL
> [Add Project] JSQCoreDataKit

- run_cperf
This alternative `run` entrypoint is for scripting a measurement of source-compat suite compilation performance of a pull request, run from CI. It has just enough options to be usable for generating local reports not-in-CI as well -- when iterating on a workstation -- but it's mostly for CI.
> Add run_cperf script

- run_cperf
Put the default output of run_cperf where CI is looking for it.
> [run_cperf] Write comment.md to ${WORKSPACE} by default.

- run_cperf
Sadly the run_cperf job appears to be being passed --output=comment.md which in turn means it will always put it in the source-compat subdirectory, not the workspace itself. This hacks around for the time being (until the job can be changed).
> [run_cperf] Hack to work around misconfiguration

- run_cperf
Adds a new pseudo-config Slava wants, switches off the -j 1 -num-threads 1 forced serialization for the time being, see whether it makes the timing too noisy or perturbs counters or whatever. It's more realistic anyways (in terms of user experience) and faster feedback might be worthwhile here.
> [run_cperf] Add debug-opt config, run multithreaded / multiprocess.

- projects.json
Fixing [SR-5998](https://bugs.swift.org/browse/SR-5998) AsyncNinja source breakage: label mismatch between closure return and contextual type
* BSD
* MIT
* MPL 2.0
* CDDL
> AsyncNinja updated. https://bugs.swift.org/browse/SR-5998 fixed

- run_cperf
Revert the verbosity-revert. Possibly this is the source of nondeterminism in reactivecocoa?
> Revert "[run_cperf] Dial back verbosity."

- run_cperf
Make sure we emit an anchor for the table, not a duplicate anchor for the reference.
> [run_cperf] Fix typo in anchor-making call.

- run_cperf
Try turning off sandbox on these tests to see if it's causing the nondet stats bug.
> [run_cperf] Try turning off sandbox (hunting nondeterminism bug)

- README.md
- project_precommit_check
This makes it clearer that the purpose of this script is a precommit check that a project/updated project is ready for submission to the source compat suite.
> Rename check to project_precommit_check.

- run_cperf
Fix a minor thinko in run_cperf's clean mode.
> [run_cperf] Only rmtree if workspace exists.

- run_cperf
This just improves error reporting for run_cperf a little bit.
> [run_cperf] Write a comment file with error before running.

- common.py
The call to 'chflags' causes linux execution of the source compat suite to fail. This fixes it.
> [common] Make call to chflags platform-conditional on Darwin

- run_cperf
This just fixes some more Darwin-isms and makes run_cperf easier to test / reuse elsewhere, and robust against unexpected failures in the testsuite.
rdar://35118643
> Misc run cperf fixes

- project.py
This enables having a per-project index store, for example, via:
--added-swift-args="-index-store-path /tmp/{path}/{branch}/index-store"
which in the swift invocations becomes:
-index-store-path /tmp/Alamofire/master/index-store
-index-store-path /tmp/SnapKit/develop/index-store
etc.
> Support substituting the values of fields in the current project's action and repo into runner.py's --added-swift-args

- projects.json
Add Swift 4.0 compatibility commit for SwiftLint.
* BSD
* MIT
* MPL 2.0
* CDDL
---
I have a few other questions that I wasn't fully able to ascertain from the current documentation.
```json
"xfail": {
"compatibility": {
"3.0": {
"branch": {
"master": "https://bugs.swift.org/browse/SR-4696",
"swift-4.1-branch": "https://bugs.swift.org/browse/SR-4696",
"swift-4.0-branch": "https://bugs.swift.org/browse/SR-4696",
"swift-3.1-branch": "https://bugs.swift.org/browse/SR-4696"
}
}
}
}
```
The referenced bug number ([SR-4696](https://bugs.swift.org/browse/SR-4696)) was closed as "not a regression". So …
> Add Swift 4.0 compatibility commit for SwiftLint

- projects.json
to resolve the xfails and point to the latest commits supporting those respective Swift versions.
As suggested by @lplarson in https://github.com/apple/swift-source-compat-suite/pull/98#issuecomment-342662717.
> Update SwiftLint's compatibility commits for Swift 3.0 & 3.1

- run_cperf
- Capture failing module names better
- Do multiple runs and average results
- Don't report baselines by default
- Report a 'brief' and 'detailed' block per config, not timers and counters
- Merge all timers
- Don't group by modules
This is the CI-side of the change https://github.com/apple/swift/pull/12962 that produces simpler/nicer compilation-performance messages. Nothing dramatically different, just making it easier to read and surfacing more-useful information / suppressing less-useful.
cc @ematejska and @airspeedswift
> [run_cperf] Miscellaneous reporting improvements to run_cperf.

- projects.json
- run
This PR adds the option to control debug and assertion options independently, and configures XFAILs for a Swift compiler with assertions enabled.
> Configure XFAILs for Swift compiler with enabled assertions

- projects.json
Reverts apple/swift-source-compat-suite#106
The swiftpm patch that caused the issue was reverted here: https://github.com/apple/swift-package-manager/pull/1402
> Revert "XFAIL Plank and R"

- projects.json
Seems to be fixed.
Reverts apple/swift-source-compat-suite#105
> Revert "XFAIL ReactiveCocoa SR-6485"

- projects.json
This PR resolves SR-4981 by advancing CoreStore's project hash.
> Resolve SR-4981

- projects.json
Resolve SRP XFAIL by advancing project hash to a version containing a fix for SR-4968.
> Resolve SRP XFAIL

- projects.json
Resolve Sourcery XFAIL by advancing project hash to a working version.
> Resolve Sourcery XFAIL

- projects.json
SwiftLint's first commit to include SWXMLHash's change to avoid conflicting with `Sequence.Element` (https://github.com/drmohundro/SWXMLHash/commit/ed5f34cc2cc87c4bcfb7ae30a25a14aa44a16c59) was https://github.com/realm/SwiftLint/commit/7acacf6bdb29414fb2cfa56a7f5bd8219fca0637, which came after SwiftLint dropped support for Swift 3.0.
So there exists no Swift 3.0 compatible commit that also supports Swift 4's `-swift-version=3` compatibility mode.
This resolves [SR-6617](https://bugs.swift.org/browse/SR-6617).
> Remove SwiftLint's 3.0 commit

- projects.json
Adds 4.0 commits for `JSQCoreDataKit` and `JSQDataSourcesKit`
* BSD
* MIT
* MPL 2.0
* CDDL
> Add 4.0 commits: JSQCoreDataKit, JSQDataSourcesKit

- projects.json
https://bugs.swift.org/browse/SR-6748
Jenkins URL: https://ci.swift.org/job/swift-master-source-compat-suite/1067
```
'Kitura' /Users/buildnode/jenkins/workspace-private/swift-master-source-compat-suite/project_cache/Kitura: error: product dependency 'KituraNet' not found
'Kitura' /Users/buildnode/jenkins/workspace-private/swift-master-source-compat-suite/project_cache/Kitura: error: product dependency 'KituraTemplateEngine' not found
```
> [XFail] Kitura due to product dependencies not found (KituraNet, KituraTemplateEngine)

- projects.json
**XFAIL GRDB**
apple/swift#13342 uses conditional conformance to make Range a Collection when its Bound is Strideable. For compatibility, CountableRange is still available as a type alias.
There is one source compatibility issue with this: currently if you extend a CountableRange with an identical method/property as Range, you will get a compilation error of a duplicate. This shouldn't really happen – specifying CountableRange should be similar to Range where Bound: Strideable but generic type aliases need an enhancement to make this work.
GRDB is the one project that does this (Foundation also did similar things but has been changed to use RangeExpression instead, avoiding the issue). XFAILing this in the compatibility test suite until the type alias change has been made.
**XFAIL …
> XFAIL GRDB and ObjectMapper

- projects.json
The bots seem to think this works on swift-4.1-branch. It reports these
as UPASS.
SR-6690 (swift-4.1-branch only)
> [4.1] Un-XFAIL ObjectMapper on swift-4.1-branch

- projects.json
This PR adds [Deferred](https://github.com/bignerdranch/Deferred), a small futures library, to the Swift compatibility suite. The specified commit builds and passes under 4.0.3 (in 3.2 and 4.0 modes) and the 4.1 beta 2 compilers.
The codebase has not had a pattern of source compatibility problems, except in early betas of major releases. Inclusion of the library might help identify those earlier in development. The code is not notably tricky in its use of Swift features, but includes uses of: C header annotations, typealiases in protocol extensions used for overloading, tuples in generics, the `Dispatch` overlay, and the modern pointer APIs.
* BSD
* MIT (✅)
* Apache License, version …
> [Add Project] Deferred

- projects.json
Updates the commit hash for one that supports the conformance changes in 4.1 (while still supporting older swift builds via swift version check) per https://bugs.swift.org/browse/SR-6556
* BSD
* MIT
* MPL 2.0
* CDDL
> Updates Sourcery hash for conformance changes

- run_cperf
This tightens up the behaviour around failed modules in the run_cperf script: now it checks on a module-by-module basis (not project-by-project) whether there were process failures, and only includes stats from non-failed modules.
rdar://37281924
> [run_cperf] Exclude modules with failures from analysis, rdar://37281924

- projects.json
- Add a Swift 4.0 hash for Result
- Set me as the maintainer since Rob is no longer involved in the project (You can see that I released [3.0](https://github.com/antitypical/Result/releases/tag/3.0.0) if you care)
- Add Linux as a supported platform because it is
> Add Swift 4.0 hash for antitypical/Result and update maintainer, platforms

- projects.json
This adds a 4.0 compatibility has for Mapper, as requested over email
> [mapper] Add 4.0 compatibility hash

- projects.json
In this PR, we have updated the Swift 4.0 compatibility support for `IBAnimatable` project. And we have run `./project_precommit_check IBAnimatable --earliest-compatible-swift-version 4.0` with Xcode 9.0.1. And the result looks as below:
```
PASS: IBAnimatable, 4.0, b565f2, IBAnimatable, generic/platform=iOS
PASS: IBAnimatable, 4.0, b565f2, IBAnimatableApp, generic/platform=iOS
Passed: 2
Failed: 0
XFailed: 0
UPassed: 0
Total: 2
Total: 1
Result: PASS
--- IBAnimatable checked successfully against Swift 4.0 ---
```
Please let me know if there are any issues, thanks. 
To be accepted into the …
> Update Swift 4.0 compatibility support for `IBAnimatable` project.

- projects.json
This pull request adds Moya 11.0.1 that support Swift 4.0.3. 
I did run `./project_precommit_check Moya --earliest-compatible-swift-version 4.0.3` with result
```
PASS: Moya, 4.0.3, 4b3ff7, Swift Package
Passed: 1
Failed: 0
XFailed: 0
UPassed: 0
Total: 1
Total: 1
Result: PASS
--- Moya checked successfully against Swift 4.0.3 ---
```
* BSD
* MIT
* MPL 2.0
* CDDL
Ensure project meets all listed …
> Updated Moya for Swift 4.0.3

- projects.json
I added the same SHA for swift 3.1 and 3.2 since PromiseKit builds against 3.1, 3.2, 3.3, 4.0 and 4.1.
I added Linux as a platform, however we only support it for 4.0 and 4.1, not 3.x. It doesn't seem possible to qualify that so advise if I should alter the `json`. Thanks
```
$  ./project_precommit_check PromiseKit --earliest-compatible-swift-version 4.0.3
** CHECK **
--- Validating PromiseKit Swift version 4.0.3 compatibility ---
--- Project configured to be compatible with Swift 4.0.3 ---
--- Checking PromiseKit platform compatibility with Darwin ---
$ /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc …
```
> Update PromiseKit for Swift 3.1, 3.2 & 4.0

- projects-cperf-smoketest.json
This should being the cperf smoketest back up to date with the main projects file. In consultation with @airspeedswift I also added SwiftLint.
> [cperf] Update project-cperf-smoketest.json to new ReactiveCocoa, add SwiftLint.

- projects.json
Updated NetService library to Swift 4.0 per Luke's request.
> Update NetService for Swift 4.0

- project_future.py
- runner.py
The flag instructs the runner to only build the most recent Swift
version specified in each project's compatibility list.
> project_future: Add --only-latest-versions flag

- projects.json
This should be reenabled again as soon as this compiler bug is fixed:
[SR-7181] Swift CI: Swift Source Compatibility Suite (master)
FAIL_RxDataSources-Pods-Pods.xcodeproj_3.0_BuildXcodeProjectTarget_Pods-Example_generic-platform-iOS.log
FAIL_RxDataSources-Pods-Pods.xcodeproj_3.0_BuildXcodeProjectTarget_Pods-RxDataSources_generic-platform-iOS.log
error: fatal error encountered during compilation; please file a bug report with your project and the crash log
<unknown>:0: note: symbol '_$S7RxSwift21AnyRecursiveSchedulerCMn' can not be undefined in a subtraction expression
> Disable an SCK project: Pods.

- projects.json
Reverts apple/swift-source-compat-suite#157
This bug is now fixed:
https://bugs.swift.org/browse/SR-7181
> Revert "Disable an SCK project: Pods."

- projects.json
Updated Swift 3.2 hash and added Swift 4.0 hash to existing CoreStore entry.
* BSD
* MIT
* MPL 2.0
* CDDL
> added 4.0 support for CoreStore

- projects.json
Added commit for Swift 4.0.3 version to Chatto project
* BSD
* MIT
* MPL 2.0
* CDDL
> Added commit for Swift 4.0.3 version to Chatto project

- projects.json
I've ran `./project_precommit_check RxSwift --earliest-compatible-swift-version 4.0.3` and here are the results.
```
** CHECK **
--- Validating RxSwift Swift version 4.0.3 compatibility ---
--- Project configured to be compatible with Swift 4.0.3 ---
--- Checking RxSwift platform compatibility with Darwin ---
$ /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc --version
$ /Users/kzaher/swift-source-compat-suite/runner.py --swift-branch swift-4.0-branch --swiftc /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bi …
```
> Adds RxSwift 4.0 compatibility.

- projects.json
I've added a Swift 4 compatible commit for R.swift
Results of `./project_precommit_check R.swift --earliest-compatible-swift-version 4.0`:
```
** CHECK **
--- Validating R.swift Swift version 4.0 compatibility ---
--- Project configured to be compatible with Swift 4.0 ---
--- Checking R.swift platform compatibility with Darwin ---
$ '/Applications/Xcode 9.0.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc' --version
$ /Users/tom/Projects/swift-source-compat-suite/runner.py --swift-branch swift-4.0-branch --swiftc '/Applications/Xcode …
```
> Add Swift 4 commit for R.swift

- projects.json
Test SwiftGraph against Swift 4.0.3
Successfully pre-checked with
```
./project_precommit_check SwiftGraph --earliest-compatible-swift-version 4.0.3
```
* BSD
* MIT
* MPL 2.0
* CDDL
> Add SwiftGraph 4.0.3 Compatibility Check

- projects.json
Project ReSwift is failing when tested against both master and swift-4.2-branch. This PR adds an xfail to ReSwift's four 3.0 configurations.
master: [Build #1520](https://ci.swift.org/job/swift-master-source-compat-suite/1520/artifact/swift-source-compat-suite/)
swift-4.2-branch: [Build #92](https://ci.swift.org/job/swift-4.2-source-compat-suite/92/artifact/swift-source-compat-suite/)
[SR-7287](https://bugs.swift.org/browse/SR-7287) has been filed to track the source breakage.
> Add xfail for ReSwift 3.0 configurations

- projects.json
A few ReactiveCocoa configurations are failing due to [SR-7299](https://bugs.swift.org/browse/SR-7299).
This adds an xfail to the 3.0, 3.2, and 4.0 configurations. (Note: 3.1 has an existing xfail which may or may not still be valid.)
> Add xfail to ReactiveCocoa 3.0, 3.2, 4.0

- projects.json
A recent Swift bug fix has disallowed code that was previously allowed, causing some source breakage. (See the following bug for more information: [SR-7273](https://bugs.swift.org/browse/SR-7273))
This PR adds an XFAIL to the 4.0 configuration of Sourcery (on master and swift-4.2-branch), until an updated hash is submitted.
Note: The XFAIL from [SR-6556](https://bugs.swift.org/browse/SR-6556) is no longer valid, and is also removed as part of this PR.
> XFAIL Sourcery 4.0 hash on master, swift-4.2-branch

- projects.json
Updates the xfailed configurations for ReactiveCocoa with the correct JIRA reference.
> Update ReactiveCocoa xfails with correct jira reference

- projects.json
1. Remove the entries for Swift 3.0 and 3.1 and their associated xfail, since the code concerned by [SR-6658](https://bugs.swift.org/browse/SR-6658) has been resolved in a later version which however does not support Swift 3.0 and Swift 3.1 due to its dependency.
2. Update the hashes for the Swift 3.2 and Swift 4.0, which resolves [SR-7299](https://bugs.swift.org/browse/SR-7299).
* BSD
* MIT
* MPL 2.0
* CDDL
> Update the compatibility suite entry of ReactiveCocoa.

- projects.json
ReactiveCocoa (3.2 and possibly 4.0) is failing in the 4.1 source compat suite.
Ultimately, the problem is the same as we've seen with some other source compat projects (like [SR-7273](https://bugs.swift.org/browse/SR-7273)) where IUOs are being used in a way that is disallowed by an update to Swift.
This issue is being tracked by [SR-7356](https://bugs.swift.org/browse/SR-7346).
> Add xfail to 3.2 and 4.0 configs of ReactiveCocoa

- projects.json
This reverts part of commit b629cb80478a97cbf859f17adf8a61b7b75ed673.
Until we're ready to merge this into the branch, it needs to stay
XFAILed there.
> Partial revert "un-XFAIL RxSwift."

- projects.json
This reverts commit f50dd084aef56d02b970f33e25493da2e9e22731.
UPASS: https://bugs.swift.org/browse/SR-7098, RxSwift, 4.0.3, 3e8487, RxCocoa-tvOS, generic/platform=tvOS
> Revert "Partial revert "un-XFAIL RxSwift.""

- project.py
- project_future.py
Xcode project files should already have information about
required SDK and it's unnecessary to try and guess it based
on the given destination.
> Xcode projects should know required SDK version

- run
Add support for passing xcodebuild arguments through `run`
command to underlying project builder configuration.
> Add `--add-xcodebuild-flags` argument to `run` command

- projects.json
These have been xfailed for some time now, and an updated hash has
not been provided. This removes the 3.1 configuration and associated
xfails.
See https://bugs.swift.org/browse/SR-6618
> Remove 3.1 configuration of ProcedureKit

- common.py
- project.py
- project_future.py
- reproduce.py
Some minimal, "safe" changes to make the code syntax compatible with both Python 2 and Python 3.
* Run __futurize --stage1__ http://python-future.org/futurize_cheatsheet.html
Python 3 syntax compatibility does __not__ mean that the port is complete.  More work may be required to complete the port to Python 3.
* BSD
* MIT
* MPL 2.0
* CDDL
> Modernize Python 2 code to get ready for Python 3

- project_precommit_check
This should allow testing of a 4.1 configuration.
> Add 4.1 configuration to project_precommit_check

- project_precommit_check
Preparing for new 4.2 submissions to the suite. Note that this version of 4.2 is what ships with Xcode beta 2.
> Add 4.2 configuration to project_precommit_check

- projects.json
Update the compatibility suite to build CleanroomLogger with SWIFT_VERSION=4.0, and drop
building for 3.0 and 3.1.
> Update hash for CleanroomLogger to build with SWIFT_VERSION=4.0

- projects.json
Update hash for Dwifft to build with SWIFT_VERSION=4.0.
For tip of `master` all the targets in Dwifft are configured to build with 4.0.
> Update hash for Dwifft to build with SWIFT_VERSION=4.0

- projects.json
- Build Kingfisher project with latest version in `master`.
- Drop building Swift 3.0 for this project.
> Update hash for Kingfisher to build with Swift 4.0

- projects.json
This updates the hash for GRDB to build with trip of master of GRDB.
Also:
- Remove building for Swift 3 (not supported in Swift 5)
- Removes redundant building for 4.1 and 4.0, as they are identical from a testing perspective.
> Update canonical hash for building GRDB with Swift 4 mode.

- projects.json
After updating the bots to Xcode 10 beta 3, we started seeing CoreStore tvOS project passing again. 
https://bugs.swift.org/browse/SR-7908
> Enable CoreStore tvOS project

- projects.json
I'm splitting up https://github.com/apple/swift-source-compat-suite/pull/197. This PR includes removing 3.x hashes for things that we're already building with 4.x.
> Remove Swift 3.x hashes for things that we're already testing with 4.x.

- projects.json
Removes the configuration to build ReactiveSwift in a few Swift 3 modes.
Project already has a current 4.0 hash.
> Drop building ReactiveSwift in 3.X modes

- projects.json
- Drop building SwiftDate in Swift 3 mode.
- Update to tip of `master` for SwiftDate when building in Swift 4 mode.
> Update hash to build SwiftDate with Swift 4

- projects.json
- Drop building SwiftGraph in 3.0 mode
- Updating to building tip-of-master for SwiftGraph in 4.0 mode
> Dropping building SwiftGraph in 3.0 mode.

- project.py
- project_future.py
- projects.json
Reverts #212 as it did not seem to resolve the issue. It looks like this change needed to land on project_future.py, because runner.py imports project_future.py, not project.py.
> [Workaround] Use old build system, avoid clean build issue

- projects.json
Some Swift Package Manager actions have been failing because of a recent change to manifest file requirements. These builds were xfailed when tested against master already in #213. This PR adds the xfail when tested against swift-4.2-branch.
See also https://bugs.swift.org/browse/SR-8234
> Also xfail Swift Package builds on 4.2

- projects.json
https://bugs.swift.org/browse/SR-6748
Newer hash seems to resolve the dependency issues as shown in SR-6748
> Updating 4.0 hash for Kitura

- projects.json
...for some package manager projects.
https://bugs.swift.org/browse/SR-8250
FAIL: AsyncNinja, 3.1, 91b80d, Swift Package --removed
FAIL: DNS, 3.1, 9e102e, Swift Package --removed
FAIL: Guitar, 3.1, f3135a, Swift Package --removed
FAIL: Guitar, 4.0, d88afd, Swift Package --xfailed
FAIL: Kronos, 4.0, 82126c, Swift Package --xfailed
FAIL: PinkyPromise, 3.0, a127ac, Swift Package --xfailed
FAIL: Serpent, 3.0, 16a3bf, Swift Package --xfailed
FAIL: Then, 3.1, daaea1, Swift Package --xfailed
FAIL: URBNJSONDecodableSPM, 3.1, 6dc998, Swift Package --xfailed
FAIL: mapper, 4.0, 45f572, Swift Package --xfailed
FAIL: mapper, 3.0, db431a, Swift Package --removed
> Add xfails for SR-8250 and remove old configurations

- project_precommit_check
This updates project_precommit_check to check 4.2 against the swift version that ships with Xcode 10 Beta 3. It also relaxes the version check so it won't fail if the Target information is slightly different.
> Update project_precommit_check's 4.2 swiftlang version

- projects.json
...but mark them as XFAILed for 3.0. We need to get a good hash for
Swift 4 and remove the 3.0 ones (and XFAILS).
> Restore the KickStarter-ReactiveExtensions and RxDataSources projects.

- projects.json
Add [SwiftyStoreKit](https://github.com/bizz84/SwiftyStoreKit) to `projects.json`.
* BSD
* MIT
* MPL 2.0
* CDDL
> Add SwiftyStoreKit

- projects.json
`local packages` 
* MIT
I need 4.2 for the local packages.  This project is using the 4.2 `local packages` feature. The sub-projects are 4.0 compatible but we use a bash script to test them individually.  
I guess we could use 4.2 to create the xcode project  but then I do not know how to specify the action to only be performed on for only a certain language.
> added xswift groups of projects

- projects.json
This new hash passes project_precommit_check when built against Xcode 10 Beta 3's Swift 4.2 compiler.
```
./project_precommit_check ObjectMapper --earliest-compatible-swift-version 4.2
** CHECK **
--- Validating ObjectMapper Swift version 4.2 compatibility ---
--- Checking ObjectMapper platform compatibility with Darwin ---
$ /Applications/Xcodes/Xcode-10-beta-3.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc --version
$ ./runner.py --swift-branch swift-4.2-branch --swiftc …
```
> Updates ObjectMapper hash to build against 4.2

- common.py
...when running swift-4.2-branch configuration.
```
./run swift-4.2-branch       
** RUN **
+ git clone -q -b swift-4.2-branch --recursive https://github.com/apple/swift-llvm.git /Users/clackary/external-src/swift-source-compat-suite/llvm
+ git clone -q -b swift-4.2-branch --recursive https://github.com/apple/swift-clang.git /Users/clackary/external-src/swift-source-compat-suite/clang
+ git clone -q -b swift-4.2-branch --recursive https://github.com/apple/swift-compiler-rt.git /Users/clackary/external-src/swift-source-compat-suite/compiler-rt
+ git clone -q -b release --recursive https://github.com/ninja-build/ninja.git /Users/clackary/external-src/swift-source-compat-suite/ninja
+ git clone -q -b swift-4.2-branch --recursive https://github.com/apple/swift.git …
```
> Use swift-4.2-branch of swift-package-manager

- projects.json
https://github.com/vapor/fluent
Adds Fluent project
* BSD
* MIT
* MPL 2.0
* CDDL
```
PASS: fluent, 4.2, 86eb88, Swift Package
Passed: 1
Failed: 0
XFailed: 0
UPassed: 0
Total: 1
Total: 1
Result: PASS
--- fluent checked successfully against Swift 4.2 ---
```
> Add Fluent project

- projects.json
The following  projects were failing to build against swift-4.2-branch because
of [SR-8234](https://bugs.swift.org/browse/SR-8234) and [SR-8250](https://bugs.swift.org/browse/SR-8250). The errors have been downgraded to warnings for Swift 4.2, but will remain errors on master. This change removes the swift-4.2-branch xfails to resolve the UPASSes on [CI](https://ci.swift.org/job/swift-4.2-source-compat-suite/445/artifact/swift-source-compat-suite/).
Deferred
GRDB.swift
Guitar
Kornos
Lark
mapper
Moya
NetService
Perfect
PinkyPromise
Plank
R.swift
Result
Serpent
SwiftLint
Then
URBNJSONDecodableSPM
> Removes swift-4.2-branch xfails (SR-8234, SR-8250)

- run
If '--distcc' is passed in, use it in the invocation of build-script.
> Refactor common leading arguments out and add --distcc.

- project_precommit_check
Update project_precommit_check's 4.2 config to the swiftlang version that ships in Xcode 10 beta 6.
```
$ swift -version
Apple Swift version 4.2 (swiftlang-1000.0.36 clang-1000.10.44)
Target: x86_64-apple-darwin18.0.0
```
> Update project_precommit_check 4.2 config to Xcode 10 beta 6

- projects.json
The xfail for https://bugs.swift.org/browse/SR-8250 is still valid, and is bumped to 4.2 along with the BuildSwiftPackage configuration.
```
./project_precommit_check Serpent --earliest-compatible-swift-version 4.2
** CHECK **
--- Validating Serpent Swift version 4.2 compatibility ---
--- Checking Serpent platform compatibility with Darwin ---
$ ./runner.py --swift-branch swift-4.2-branch --swiftc …
```
> Update Serpent hash to 4.2

- projects.json
The xfail for https://bugs.swift.org/browse/SR-8250 is still valid, and is bumped to 4.2 along with the BuildSwiftPackage configuration.
```
./project_precommit_check PinkyPromise --earliest-compatible-swift-version 4.2
** CHECK **
--- Validating PinkyPromise Swift version 4.2 compatibility ---
--- Checking PinkyPromise platform compatibility with Darwin ---
$ ./runner.py --swift-branch swift-4.2-branch …
```
> Update PinkyPromise hash to 4.2

- .gitignore
- cleanup
- common.py
- projects.json
- run_sk_stress_test
- runner.py
- sourcekit-xfails.json
The run_sk_stress_test script invokes runner.py passing sk-swiftc-wrapper to `--swiftc`. This wrapper invokes swiftc, forwarding its own arguments on to it. If the swiftc invocation succeeds it them invokes sk-stress-test, which stress tests SourceKit on all the .swift files in the passed compiler arguments.
As invoking swiftc and the stress tester takes significantly longer than swiftc alone, the script tries to bring down the runtime without sacrificing too much coverage by:
1. only running over the latest swift compatibilty version supported by each repo
2. only running over one of each set of platform-specific actions/schemes (e.g. just RxSwift-macOS, rather than that + RxSwift-iOs, RxSift-tvOS, etc.)
3. only building generic/iOS actions for arm64, rather than arm64 and armv7
This …
> Add run_sk_stress_test script to run the SourceKit stress tester over the source compatibility suite

- projects.json
Updates the hash to a recent commit, and also updates the configuration to build against Swift 4.2. Also removes the xfail from https://bugs.swift.org/browse/SR-8250.
```
./project_precommit_check Then --earliest-compatible-swift-version 4.2
** CHECK **
--- Validating Then Swift version 4.2 compatibility ---
--- Checking Then platform compatibility with Darwin ---
$ ./runner.py --swift-branch swift-4.2-branch …
```
> Update Then hash to build against 4.2

- projects.json
Updates the hash to be built against Swift 4.2. Also removes the xfail from the 4.0 configuration, because of [SR-8234](https://bugs.swift.org/browse/SR-8234).
```
PASS: Perfect, 4.2, cdc17d, Swift Package
Passed: 1
Failed: 0
XFailed: 0
UPassed: 0
Total: 1
Total: 1
Result: PASS
```
> Update Perfect hash to build against 4.2

- projects.json
Updates the hash to be built against Swift 4.2. Also removes the xfail from the 4.0 configuration, because of [SR-8234](https://bugs.swift.org/browse/SR-8234).
```
PASS: Plank, 4.2, 71a3a5, Swift Package
Passed: 1
Failed: 0
XFailed: 0
UPassed: 0
Total: 1
Total: 1
Result: PASS
```
> Update Plank hash to build against 4.2

- projects.json
Updates the hash to be built against Swift 4.2. Also removes the xfail from the 4.0 configuration, because of [SR-8234](https://bugs.swift.org/browse/SR-8234).
```
PASS: R.swift, 4.2, f96758, Swift Package
Passed: 1
Failed: 0
XFailed: 0
UPassed: 0
Total: 1
Total: 1
Result: PASS
```
> Update R.swift hash to build against 4.2

- projects.json
Updates the hash to be built against Swift 4.2. Also removes the xfail from the 4.0 configuration, because of [SR-8234](https://bugs.swift.org/browse/SR-8234).
```
PASS: Result, 4.2, 2fe5b3, Swift Package
Passed: 1
Failed: 0
XFailed: 0
UPassed: 0
Total: 1
Total: 1
Result: PASS
```
> Update Result hash to build against 4.2

- projects.json
Previously Mapper used a Swift 3 style Package.swift. Now on master this
has been updated to be a 4.2 format manifest, that supports building 4.0
I'm not sure if this format is correct, I updated the sha for 4.0, and added 4.1, but with the current Mapper configuration these still have to be built with the 4.2 compiler, just in 4.0 mode.
> Fix Mapper SwiftPM compatibility

- projects.json
Previously Kronos used a Swift 3 style Package.swift. Now on master this
has been updated to be a 4.2 format manifest, that supports building 4.0
> Fix Kronos SwiftPM compatibility

- projects.json
This PR adds a SwiftLint Swift 4.2 compatibility version hash and removes the xfail.
* BSD
* MIT
* MPL 2.0
* CDDL
```
$ ./project_precommit_check SwiftLint --earliest-compatible-swift-version 4.2
** CHECK **
--- Validating SwiftLint Swift version 4.2 compatibility ---
--- Checking SwiftLint platform compatibility with Darwin ---
$ …
```
> Add SwiftLint Swift 4.2 compatibility version hash

- project.py
- project_future.py
- projects.json
Verified locally: 
```
PASS: AMScrollingNavbar, 4.0, de70ea, AMScrollingNavbar, generic/platform=iOS
PASS: Alamofire, 3.0, b03b43, Alamofire iOS, generic/platform=iOS
PASS: Alamofire, 3.0, b03b43, Alamofire macOS, generic/platform=macOS
PASS: Alamofire, 3.0, b03b43, Alamofire tvOS, generic/platform=tvOS
PASS: Alamofire, 3.0, b03b43, Alamofire watchOS, generic/platform=watchOS
PASS: Alamofire, 3.0, b03b43, iOS Example, generic/platform=iOS
PASS: AsyncNinja, 4.0, efc83b, AsyncNinja, generic/platform=macOS
PASS: AsyncNinja, 4.0, efc83b, AsyncNinja, generic/platform=iOS
PASS: AsyncNinja, 4.0, efc83b, AsyncNinja, generic/platform=tvOS
PASS: AsyncNinja, 4.0, efc83b, AsyncNinja, generic/platform=watchOS
PASS: AsyncNinja, 4.0, efc83b, Swift Package
UPASS: https://bugs.swift.org/browse/SR-8234, …
```
> Only build watchOS project for armv7k <rdar://problem/44522408>

- project_precommit_check
Update the swiftlang version in project_precommit_check to check against the version in Xcode 10.0.
```
$ ./project_precommit_check Evergreen --earliest-compatible-swift-version 4.2
** CHECK **
--- Validating Evergreen Swift version 4.2 compatibility ---
--- Checking Evergreen platform compatibility with Darwin ---
$ /Applications/Xcodes/Xcode-10-GM.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc --version
$ ./runner.py --swift-branch swift-4.2-branch --swiftc …
```
> Update swiftlang version to check against Xcode 10.0's

- projects.json
Changed the commit hash and version for an Xcode 10 / Swift 4.2 compatible version:
```json
"compatibility": [
{
"version": "4.2",
"commit": "a5b3a0ff480e44f5183a1a39a859f77eaa05f9d0"
}
],
```
* BSD
* MIT
* MPL 2.0
* CDDL
> Update Guitar to build against 4.2

- projects.json
https://bugs.swift.org/browse/SR-7233
The crytpo, http, and websocket dependencies for vapor all depend
on libressl, which isn't available in CI. This adds the other
dependencies as individual projects.
* MIT
```
./runner.py --swift-branch swift-4.2-branch --swiftc /Applications/Xcodes/Xcode_10_Beta_6.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc --projects projects.json --include-repos 'path.startswith("vapor_")' --include-versions 'version == "4.2"' --include-actions 'action.startswith("Build")'
PASS: vapor_console, 4.2, 5b9796, Swift Package
PASS: vapor_core, 4.2, 08a576, Swift Package
PASS: vapor_database-kit, 4.2, 3a17db, Swift Package
PASS: vapor_multipart, 4.2, e57007, Swift …
```
> Separate vapor project into subcomponents (SR-7233)

- projects.json
This adds https://github.com/pointfreeco/swift-overture.
* BSD
* MIT 👈
* MPL 2.0
* CDDL
> Add swift-overture

- projects.json
Adds xfail to fluent and SwiftLint due to https://bugs.swift.org/browse/SR-9029
> Xfail fluent and SwiftLint due to SR-9029

- projects.json
This reverts commit 70ddb3726b8d69ba06c9f1f69dd9210184284035.
I fixed these in:
https://github.com/apple/swift/pull/19959
> Revert "Xfail fluent and SwiftLint due to SR-9029"

- projects.json
NetService used the out-dated, unsupported PackageDescription v3. It has been updated to work with Swift 4.2. I'm not 100% sure about it passing the CI here, but that's easy to find out :).
> Update NetService to Swift 4.2, resolves XFAIL

- projects.json
This adds https://github.com/pointfreeco/swift-tagged to the source compatibility suite. It relies on conditional conformance to be useful and is Swift 4.1-compatible.
* BSD
* MIT 👈
* MPL 2.0
* CDDL
---
I've left one item unchecked since this library, relying heavily on conditional conformance, requires Swift 4.1. I hope the value proposition makes this worth inclusion regardless.
> Add swift-tagged

- projects.json
This adds https://github.com/pointfreeco/swift-nonempty to the source compatibility suite. It is Swift 4.1-compatible and Swift 4.2 has introduced a regression: https://bugs.swift.org/browse/SR-8985
* BSD
* MIT 👈
* MPL 2.0
* CDDL
---
I've left one item unchecked since this library, relying heavily on conditional conformance, requires Swift 4.1. I hope the value proposition makes this worth inclusion regardless.
> Add swift-nonempty

- projects.json
- Drop building Swift 3 variant of this project.
- Update to tip of `master` for building project in Swift 4 mode.
> For JSQCoreDataKit drop building Swift 3, and update to tip for Swift 4

- projects.json
Added ModelAssistant Repository to **Projects.json**
* MIT
> Add ssamadgh/ModelAssistant to suite

- projects.json
Adds xfail to NonEmpty on swift-4.2-branch because it's hitting an assertion failure (see https://bugs.swift.org/browse/SR-9111).
> Also xfail NonEmpty on swift-4.2-branch

- projects.json
Reverts apple/swift-source-compat-suite#271
> Revert "Also xfail NonEmpty on swift-4.2-branch"

- projects.json
This is done as part of the work for [SR-8174](https://bugs.swift.org/browse/SR-8174).
> Drop Swift 3.0 configuration for JSQDataSourcesKit

- projects.json
Also add xfail of ProcedureKitCloud due to https://bugs.swift.org/browse/SR-9139
```
$ ./project_precommit_check ProcedureKit --earliest-compatible-swift-version 4.2
** CHECK **
--- Validating ProcedureKit Swift version 4.2 compatibility ---
--- Checking ProcedureKit platform compatibility with Darwin ---
$ /Applications/Xcodes/PublicGMs/Xcode-10-GM.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc --version
$ ./runner.py --swift-branch swift-4.2-branch --swiftc …
```
> Update ProcedureKit to build against Swift 4.2

- projects.json
```
$ ./project_precommit_check ReSwift --earliest-compatible-swift-version 4.2     
** CHECK **
--- Validating ReSwift Swift version 4.2 compatibility ---
--- Checking ReSwift platform compatibility with Darwin ---
$ /Applications/Xcodes/PublicGMs/Xcode-10-GM.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc --version
$ ./runner.py --swift-branch swift-4.2-branch --swiftc /Applications/Xcodes/PublicGMs/Xcode-10-GM.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc --projects …
```
> Update ReSwift to build against Swift 4.2

- projects.json
Updates the RxDataSources configuration to use SwiftPM. The Xcode project configurations were removed because of a missing RxSwift dependency.
```
$ ./project_precommit_check RxDataSources --earliest-compatible-swift-version 4.2
** CHECK **
--- Validating RxDataSources Swift version 4.2 compatibility ---
--- Checking RxDataSources platform compatibility with Darwin ---
$ /Applications/Xcodes/PublicGMs/Xcode-10-GM.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc --version
$ ./runner.py --swift-branch …
```
> Update RxDataSources to build against Swift 4.2

- projects.json
- Updated maintainer details
- Added Kickstarter iOS app
> Update hash for Kickstarter-Prelude and Kickstarter-ReactiveExtensions

- projects.json
Swift CI: 2. Swift Source Compatibility Suite (master) - SILCloner crash in LetPropertiesOpt
> XFAIL IBAnimatable: SR-9146

- projects.json
Updates the hash to a recent commit, and also updates the configuration to build against Swift 4.2. Also removes the xfail from https://bugs.swift.org/browse/SR-8234. 
```
./project_precommit_check GRDB.swift --earliest-compatible-swift-version 4.2
** CHECK **
--- Validating GRDB.swift Swift version 4.2 compatibility ---
--- Checking GRDB.swift platform compatibility with Darwin ---
$ ./runner.py …
```
> Update GRDB.swift hash to build against 4.2

- projects.json
Updates `JSQCoreDataKit` for Swift 4.2
* BSD
* MIT
* MPL 2.0
* CDDL
> [JSQCoreDataKit] update for swift 4.2

- project_future.py
- projects.json
Currently if both major and minor versions as specified minor would
be stripped out and only major gets set in actual `xcodebuild` flags,
but `4.2` is a valid version which has to be supported.
> Fix builder factory to handle Swift version 4.2 correctly

- projects.json
...until we cherry-pick a fix there.
> Keep ModelAssistant XFAILed on swift-5.0-branch.

- .gitignore
- cleanup
- projects.json
- run_sk_stress_test
- sourcekit-xfails.json
Updates the `run_sk_stress_test` script for various  SourceKit stress tester and SwiftSyntax build and functionality changes:
- update script to account for swift-syntax now being in its own repo, rather than swift's
- xfail tracking is now handled by the stress tester itself, so remove it from the script, and update the xfails file for the new format.
- Update the xfails file with the latest issues (from a full run over the weekend).
- The SourceKit stress tester build is now handled by Swift's build-script so stop building it separately and update the build-script invocation for the toolchain with the new flags.
- Refine the set of projects with the `sourcekit-smoke` tag (due to various new checks in the stress tester, the previous set started taking too long).
- Remove the `sourcekit` …
> Update the SourceKit stress tester run script for recent changes to the stress tester

- projects.json
Un-XFAIL ModelAssistant on the swift-5.0-branch once
https://github.com/apple/swift/pull/20971 is merged.
> Revert "Keep ModelAssistant XFAILed on swift-5.0-branch."

- projects.json
This PR contains the setting for LineSDK project (https://github.com/line/line-sdk-ios-swift).
It is suggested by @jrose-apple in https://bugs.swift.org/browse/SR-9375 and contains a crash for Swift 5 toolchain (Swift Development Snapshot 2018-11-28 (a)).
* BSD
* MIT
* MPL 2.0
* CDDL
> Add LineSDK to compatibility suite

- projects.json
These projects report as UPASS in PR testing of 5.0 branch
> Un-XFAIL Lark, SRP, SwiftLink on swift-5.0-branch

- projects.json
Reverts apple/swift-source-compat-suite#302. These projects should be fixed by https://github.com/apple/swift/pull/21370
> Revert "XFAIL projects using non-stdlib Result"

- projects.json
It was un-xfailed as part of reverting the Result xfails, but its underlying issue (https://bugs.swift.org/browse/SR-9505) is different and still a problem.
> Restore vapor_routing xfail

- projects.json
Adding Xfails for current failures:
FAIL: Lark, 4.0, 7604f9, Swift Package -> https://bugs.swift.org/browse/SR-8234
FAIL: SRP, 4.0, b16683, Swift Package -> https://bugs.swift.org/browse/SR-9543
FAIL: SwiftLint, 4.2, 60f98e, Swift Package -> https://bugs.swift.org/browse/SR-9543
FAIL: SwiftLint, 4.0, 60f98e, Swift Package -> https://bugs.swift.org/browse/SR-9543
FAIL: vapor_routing, 4.2, 3219e3, Swift Package -> https://bugs.swift.org/browse/SR-9505
> Update swift-5.0-branch xfails

- projects.json
- run_sk_stress_test
Remove Surge from the set of 'sourcekit-smoke' projects and fix the number of failures reported in the summary output to reflect the number of individual failures in addition to the number of unique issue urls they're associated with.
> [run_sk_stress_test] Reduce the set of projects to test and update the summary output

- projects.json
Added commit hash for CoreStore's Swift 4.2 support.
* BSD
* MIT
* MPL 2.0
* CDDL
> Added Swift 4.2 commit for CoreStore

- run_cperf
Commit 6952162 (which seems to have been pushed directly to master) appears to have inadvertently fixed a prior bug in the run_cperf script which was causing it to save its output file in the wrong place. Unfortunately, it also broke the hack which was copying the file to the *right* place, causing all compiler performance tests to raise an error right before the comment with the results was posted to Github.
This PR removes the hack, which I believe will at least partially fix compiler performance tests. We may still need to XFAIL a few projects or something, but we should at least get the comment now.
Tagging @shahmishal, because I'm hoping there's a way to test this on the CI before merging it, and if there is I think he'll know how to do it.
> Fix bug in compiler performance test script

- projects.json
Added Swift 5.0 config with Swift 4.2 SHA to test Swift compiler with `-swift-version 5` flag.
Projects added with Swift 5.0 config: 
- AMScrollingNavbar
- BlueSocket
- Deferred
- fluent
- GRDB.swift
- Guitar
- Html
- JSQCoreDataKit
- KeychainAccess
- kommander
- Kronos
- line-sdk-ios-swift
- mapper
- ModelAssistant
- NetService
- ObjectMapper
- Overture
- Perfect
- PinkyPromise
- Plank
- ProcedureKit
- R.swift
- Result
- ReSwift
- RxDataSources
- Surge
- swift-nio
- SwiftLint
- SwiftyJSON
- Then
- vapor_console
- vapor_core
- vapor_database-kit
- vapor_multipart
- vapor_routing
- vapor_service
- vapor_template-kit
- vapor_url-encoded-form
- vapor_validation
Projects xFailed:
- CoreStore
- Deferred
- exercism-swift
- PinkyPromise
- ProcedureKit
- Serpent
Tested locally with master …
> Add Swift 5.0 config for source compat projects

- sourcekit-xfails.json
Also update them to account for the latest weekly master CI results.
> Update stress tester xfails to separate 5.1 branch and master

- sourcekit-xfails.json
It now hits a different crash at a later offset in the same file.
> Update sourcekit xfails for a fixed code completion issue

- project_precommit_check
Updates `project-precommit-check` with a Swift 5.0 configuration.
> Add config for Swift 5.0 to project-precommit-check

- projects.json
Some issues were resolved to build/test Lark against Swift 4.2. Travis CI succeeds, so that's looking good. I'm not 100% sure about it passing the CI here, but that's easy to find out :).
> Update Lark to Swift 4.2, resolves XFAIL

- projects.json
Updates the 5.0 hash for CoreStore.
rdar://49270199
> Update 5.0 hash for CoreStore

- projects.json
The “DNS”, “Guitar”, and “Result” projects are failing to build in SourceKit stress tests, apparently because of a bad interaction between SKStressTester’s swiftc wrapper and SwiftPM. Temporarily remove these projects from stress tester tests.
rdar://problem/50584688
> Don’t SKStressTest certain projects

- sourcekit-xfails.json
Now that the CI job configuration has been fixed, this apparently needs to be removed entirely. rdar://50695868
> Remove apparently fixed Dollar SourceKit XFAIL harder

- projects.json
- run_sk_stress_test
Sets an environment variable to suppress progress and detected failure output from sk-swiftc-wrapper and instead dump the failures at the end of the run based on what's in the results JSON file. This is to work around the CI job failing with SwiftPM projects due to the extra inline output sk-swiftc-wrapper produces on top of the wrapped compiler output not being parseable when SwiftPM builds pass
`-parseable-output`. The extra output is all on stderr as far as I can tell, which used to be enough for SwiftPM to ignore it, but something changed and I'm not sure what. This works around the problem in the meantime.
This PR also adds back the SwiftPM projects that we stopped stress testing because of this issue. The stress tester side changes that suppress output based on the environment …
> [run_sk_stress_test] List all failures at the end of the run

- sourcekit-xfails.json
xfails the new issues it now finds.
> [run_sk_stress_test] Update sourcekit-xfails.json for recent stress tester changes

- run_sk_stress_test
Hopefully fixes the below error due to trying to print '©' in the stress tester CI jobs:
> UnicodeEncodeError: 'ascii' codec can't encode character u'\xa9' in position 2673: ordinal not in range(128)
> [run_sk_stress_test] Replace non-ascii characters when outputting to an ascii tty

- sourcekit-xfails.json
Update `sourcekit-xfails.json` after https://github.com/apple/swift/pull/25912
rdar://problem/52386176
> [sourcekit-stress-tester] Update sourcekit-xfails.json

- project_precommit_check
Update project_precommit_check with 5.1 configuration to the swiftlang that shipped in Xcode 11 Beta 3.
> Update project_precommit_check with 5.1 configuration

- sourcekit-xfails.json
These were caused by a bug in the stress tester (fixed here: https://github.com/apple/swift-stress-tester/pull/76)
> [run_sk_stress_test] Update sourcekit xfails for a stress-tester side fix

- projects.json
Now that these bugs are fixed, we can reenable R.swift and RxDataSources.
> Un-XFAIL SR-11135 and SR-11136

- projects.json
I added this project in a separate build because it's slightly different
to the other repositories of the SwiftNIO family. Almost everything is
pure Swift but swift-nio-ssl contains a vendored (and symbol-prefixed)
version of BoringSSL.
I think it's a project that's very unlike most other Swift projects so I
think it's valuable but wanted to make it a separate PR.
* Apache 2 for the NIO and grpc bits
* Combination ISC and OpenSSL license for BoringSSL
> add swift-nio-ssl

- projects.json
Adds a configuration to build projects against Swift 5.1 (from Xcode 11 beta 3).
Some projects required an update to the schemes.
AMScrollingNavbar
Alamofire
AsyncNinja
BeaconKit
BlueSocket
CoreStore
cub
DNS
Dollar
Dwifft
exercism-swift
GRDB.swift
Guitar
Html
IBAnimatable
JSQCoreDataKit
KeychainAccess
Kickstarter-ReactiveExtensions
Kingfisher
Kitura
Kronos
Lark
line-sdk-ios-swift
Moya
NonEmpty
ObjectMapper
Overture
Perfect
PinkyPromise
Plank
ProcedureKit
PromiseKit
R.swift
Re-Lax
ReSwift
ReactiveCocoa
ReactiveSwift
Result
RxSwift
SRP
Serpent
Sourcery
Starscream
Surge
SwiftGraph
SwiftLint
SwifterSwift
swift-nio
SwiftyJSON
SwiftyStoreKit
Tagged
Then
kommander
launchscreensnapshot
mapper
siesta
vapor_console
vapor_core
vapor_multipart
vapor_routing
vapor_service
vapor_template-kit …
> Update projects with 5.1 configurations

- projects.json
The project's main target is to show dynamic updates between two text fields. ( With or without publishers. )
The main task is to convert base64 encoded string to valid json and vice versa.
> projects: Base64CoderSwiftUI has been added.

- project_precommit_check
Allows `--swiftc` flag to be honored when passed to `project_precommit_check` on Darwin platforms. The version check must be relaxed for the this to work. Also provides relevant warnings that an unexpected swiftlang version is being used.
> [project_precommit_check] Add warning when passing --swiftc on Darwin

- project_precommit_check
Updating project_precommit_check to match the swiftc versions that shipped in Xcode 11 beta 5.
```
$ swiftc --version
Apple Swift version 5.1 (swiftlang-1100.0.266.1 clang-1100.0.32.1)
Target: x86_64-apple-darwin18.5.0
```
> Update 5.1 configuration to match beta 5

- projects.json
Updating project sources for PinkyPromise and Serpent to resolve the failure seen in [SR-8250](https://bugs.swift.org/browse/SR-8250). Only affects the 4.2 and 5.0 configurations.
> Update PinkyPromise and Serpent hashes

- projects.json
3.0 configuration no longer exists, and the xfail is no longer needed.
> Remove unnecessary xfail for Kickstarter

- projects.json
https://bugs.swift.org/browse/SR-9899
This required project side changes, which appear to have been addressed. Adds a new 5.1 configuration, and removes the xfail from 4.2 and 5.0 configurations.
```
PASS: Deferred, 5.1, 0ce7e5, Swift Package
$ git -C project_cache/Deferred rev-parse --show-toplevel
PASS: Deferred, 5.1, 0ce7e5, MobileDeferred, generic/platform=iOS
$ git -C project_cache/Deferred rev-parse --show-toplevel
PASS: Deferred, 5.1, 0ce7e5, TVDeferred, generic/platform=tvOS
$ git -C project_cache/Deferred rev-parse --show-toplevel
PASS: Deferred, 5.1, 0ce7e5, NanoDeferred, generic/platform=watchOS
Passed: 4
Failed: 0
XFailed: 0
UPassed: 0
Total: 4
Total: 1 …
```
> Update Deferred project with 5.1 hash

- projects.json
> [Add] NSAttributedStringBuilder

- projects.json
[SR-8307](https://bugs.swift.org/browse/SR-8307) appears to be resolved by using newer project sources.
Updates the configuration for both `exercism-swift` and `exercism-xswift`.
> Update exercism project configurations for Swift 5.1

- projects.json
https://bugs.swift.org/browse/SR-11136
Issue appears to be resolved as of Xcode 11 beta 5. Removes associated xfail.
```
$ ./runner.py --swift-branch master --swiftc /Applications/Xcodes/Xcode-11.0-beta-5.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc --projects projects.json --include-repos 'path == "RxSwift"' --include-versions 'version == "5.1"' --include-actions 'action.startswith("Build")'
...
UPASS: https://bugs.swift.org/browse/SR-11141, RxSwift, 5.1, 70b8a3, RxCocoa, platform=macOS
```
> Remove xfail for RxSwift/RxCocoa

- projects.json
Failure - `error: no type named 'ManagedAudioChannelLayout' in module 'CoreAudio'`
> XFAIL SwifterSwift due to SR-11248

- projects.json
Reverts apple/swift-source-compat-suite#372
Looks like this issue remains unfixed yet.
> Revert "Remove xfail for RxSwift/RxCocoa"

- sourcekit-xfails.json
The stress tester job is currently failing because of this: https://ci.swift.org/job/swift-master-sourcekitd-stress-tester/1120/
> [run_sk_stress_test] Removed fixed stress tester xfail

- sourcekit-xfails.json
To get the stress tester CI job blue again:
https://ci.swift.org/job/swift-master-sourcekitd-stress-tester/1128/
> [run_sk_stress_test] Remove fixed stress tester xfail in Dollar.swift

- README.md
- project.py
- project_future.py
- projects.json
Starscream is failing only in release configuration at the moment and there was no way to XFAIL release but not debug previously.
This change also reworks how xfail matching works to be more expressive, since it could previously only match either branches or platforms for a specific compatibility version, not both. See the `README.md` changes for details.
Migrated `projects.json` to the new structure (`projects-incremental.json` has no xfails currently) and updated the starscream xfail to be release only. It still supports the old structure to allow time to update the json in downstream repos. I'll remove it once that happens.
> Add support for xfailing based on build configuration (release vs debug)

- run_sk_stress_test
Otherwise SwiftSyntax can't find it and the stress tester is unable to run. Should unblock the CI failure https://ci.swift.org/job/swift-master-sourcekitd-stress-tester/1392/.
> Install the parser library when running the stress tester

- projects.json
Should resolve an issue building with SwiftPM on case-sensitive
filesystems.
Resolves rdar://56786088
> Xfail Sourcery hash for 5.1

- projects.json
Reverts apple/swift-source-compat-suite#394
Was fixed by https://github.com/apple/swift/pull/28206.
> Revert "XFail Bow"

- projects.json
Adds swift-futures: https://github.com/dfunckt/swift-futures
Futures is a relatively large library, makes heavy use of value types and generics (which seem to be stressing the compiler quite a bit) and also includes a C target, which overall I think make for a valuable addition to the source compatibility suite.
* BSD
* MIT
* MPL 2.0
* CDDL
> Add swift-futures

- project.py
- project_future.py
They only need it if they also have an xfail entry with a configuration field, and no overriding configuration was specified via the `--build-config` flag.
> Don't assume all xfailed actions have a 'configuration' specified

- projects-cperf-smoketest.json
All of the projects in `smoke test compiler performance` currently fail.
> [perf_test] Update performance `smoke test` project configurations

- projects.json
Adds [ReactiveKit](https://github.com/DeclarativeHub/ReactiveKit). 
This PR supersedes #325.
* BSD
* MIT
* MPL 2.0
* CDDL
I wasn't sure which iOS Simulator device to use - I've chosen an iPhone 11. Please let me know if this isn't suitable.
> Add ReactiveKit

- project_future.py
- runner.py
Useful for comparing project binary sizes between two different swift compilers
> Add a new option to runner.py to accept alternate project_cache paths

- project_future.py
We're seeing a collision in some sandbox rules. Since we're using our own sandbox in the source compat suite, we can disable the one coming from package support.
For now, this will add `-IDEPackageSupportDisableManifestSandbox=YES` to each invocation of xcodebuild, which should be a no-op for non-package projects, and would likely be the right thing to do for all package projects.
rdar://53518566
> Add flag to xcodebuild to disable manifest sandbox

- run_cperf
This beyond making it easier to maintain this over time, also (due to the preset
already doing this) solves an issue where the compiler perf suite couldn't build
swiftpm since it was not installing dsymutil into the just installed toolchain.
> [cperf] Change cperf to use source compat preset to ensure.

- run_cperf
I assumed that these originally existed when I added the build-script preset
code for run_cperf. Now we can select the appropriate preset without issue. By
default that is release no-assertions.
> Update run_cperf with 3 extra options needed by the build-script preset code.

- projects.json
This PR adds [CareKit](https://github.com/carekit-apple/CareKit) to the source compatibility suite.
* BSD
* MIT
* MPL 2.0
* CDDL
> Add CareKit to the projects list

- projects.json
Add [MovieSwiftUI](https://github.com/Dimillian/MovieSwiftUI)
* BSD
* MIT
* MPL 2.0
* CDDL
> [Add] MovieSwiftUI

- projects.json
TL;DR: Attempting to add SwiftPM tests only for the newest version of Siesta, but preserve the existing Xcode-only config for older versions. Is this PR the proper way to accomplish that?
---
Siesta has been in the compatibility suite since the suite’s earliest days, as an Xcode-only project.
Siesta’s test suite depends on Quick and Nimble. When building as an Xcode project, Carthage manages those dependences, and swift-source-compat-suite thus can’t run the tests. However, at long last, I got Siesta working with SwiftPM (yay!), and now swift-source-compat-suite is capable of running Siesta’s tests via SwiftPM.
There is value in adding those tests to your suite, I think: there are some quirks in them you probably want in your regression tests. (In fact, as of last week, Siesta’s tests …
> Added SwiftPM build of Siesta

- project_future.py
The SPM that is being used to build projects is the just built SPM.  Consequently, it may depend on changes present in the just-built libraries but absent from the libraries in the OS.
Here, those just built libraries are used by SPM by setting DYLD_LIBRARY_PATH to the directory of just built macosx libraries in the environment in which swift build is run.
> Use built libraries when running SPM builds.

- projects.json
It's currently not running. This reduces the project set to match the short run job temporarily so it will pass, and I'll gradually add projects back as I file bug reports and add xfails for any issues they're hitting.
> [run_sk_stress_test] Temporarily remove most projects from the long-running stress tester job

- projects.json
Add [ACHNBrowserUI](https://github.com/Dimillian/ACHNBrowserUI) a full featured SwiftUI application
* BSD
* MIT
* MPL 2.0
* CDDL
> [Add] ACHNBrowserUI

- projects.json
Base64CoderSwiftUI is currently xfailed, due to the following [failure](https://ci.swift.org/job/swift-master-source-compat-suite/5010/artifact/swift-source-compat-suite/XFAIL_Base64CoderSwiftUI-Base64CoderSwiftUI.xcodeproj_5.1_BuildXcodeProjectTarget_Base64CoderSwiftUI_generic-platform-iOS.log)...
```
/Users/buildnode/jenkins/workspace/swift-master-source-compat-suite/swift-source-compat-suite/project_cache/Base64CoderSwiftUI/Base64CoderSwiftUI/Model.swift:169:24: error: cannot find type 'BindableObject' in scope
class PublishersModel: BindableObject {
^~~~~~~~~~~~~~
```
The newest commit may address this failure on the project side.
> Update hash for Base64CoderSwiftUI

- runner.py
- sourcekit-xfails.json
They were being concatenated without adding a leading space to separate them
from the preceding arguments, breaking some project builds in the stress tester CI jobs (which pass extra xcodebuild flags).
Also updates the xfails for run_sk_stress_test now that the broken projects are building, and for some recent fixes.
> [runner.py] Fix args passed via --add-xcodebuild-flags not being concatenated properly

- projects.json
The following projects/configurations were xfailed:
fluent, 5.0, Swift Package
fluent, 4.2, Swift Package
Kitura, 5.1, Swift Package
Kitura, 4.0, Swift Package
Moya, 5.1, Swift Package
SRP, 5.1, Swift Package
SRP, 4.0, Swift Package
Sourcery, 5.1, Swift Package
SwiftLint, 5.1, Swift Package
SwiftLint, 5.0, Swift Package
SwiftLint, 4.2, Swift Package
SwiftLint, 4.0, Swift Package
siesta, 5.1, Swift Package
vapor_console, 5.0, Swift Package
vapor_console, 4.2, Swift Package
vapor_database-kit, 5.0, Swift Package
vapor_database-kit, 4.2, Swift Package
vapor_multipart, 5.1, Swift Package
vapor_multipart, 5.0, Swift Package
vapor_multipart, 4.2, Swift Package
vapor_routing, 5.0, Swift Package
vapor_routing, 4.2, Swift Package
vapor_service, 5.0, Swift Package
vapor_service, 4.2, Swift Package …
> Xfailed a number of projects.

- projects.json
Example of failure:
https://ci.swift.org/view/Dashboard/job/swift-master-source-compat-suite-debug/3301/consoleText
> Xfail ACHNBrowserUI, 5.1, generic/platform=iOS.

- projects.json
Example failure:
https://ci.swift.org/view/Source%20Compatibility/job/swift-5.3-master-source-compat-suite-debug/154/consoleText
https://bugs.swift.org/browse/SR-13198
> Xfail ACHNBrowserUI/5.1, platform=iOS on 5.3.

- projects.json
Reverts apple/swift-source-compat-suite#460. These should have been fixed by https://github.com/apple/swift/pull/34102.
> Revert "Xfail siesta and siesta-legacy"

- projects.json
Remove XFAILs associated with unsupported compatibility
versions and swift branches.
> Audit and cleanup XFAILs in projects.json

- projects.json
This addresses the Source Compatibility Suite failure
```
error: The linked and embedded framework 'Sparkle.framework' is missing
one or more architectures required by this target: arm64. (in target
'Evergreen' from project 'Evergreen')
```
Addresses rdar://70533579
> Build Evergreen 4.0 x86_64 only

- projects.json
Debug builds are UPASS'ing on main right now - https://ci.swift.org/view/Source%20Compatibility/job/swift-main-source-compat-suite-debug/3600/artifact/swift-source-compat-suite/
> Un-XFAIL ACHNBrowserUI in debug configuration (main branch)

- projects.json
ACHNBrowserUI is UPASSing for 5.3: https://ci.swift.org/job/swift-5.3-master-source-compat-suite-debug//302/console
> Un-XFAIL ACHNBrowserUI in debug configuration (5.3 branch)

- projects.json
- run
This pull request does two things in support of a future Swift Package Manager-specific compatibility test mode:
All existing projects with `BuildSwiftPackage` actions now also have a "swiftpm" tag added to those actions. This will control what gets run for SwiftPM compatibility testing and I imagine it should work similarly to how the sourcekit stuff is used now:
- New projects opt in by adding the "swiftpm" tag.
- Projects are temporarily disabled by switching to the "swiftpm-disabled" tag.
- Existing projects that have been opted-in can choose not to participate by removing the tag entirely.
I'm not set on "swiftpm" as the name of this tag, but it's concise and consistent with existing build flags. 
This brings the `--filter-by-tag` argument [from the sourcekit …
> Add --filter-by-tag to run script and "swiftpm" tag to relevant project actions

- projects.json
The library `RxReactiveObjC` is already in the suite. 
I've recently made the library to support Swift Package Manager.  
This way of integration is better as the previous one was using a special branch to work around the fact that the compat suite doesn't support CocoaPods.
* MIT
> update RxReactiveObjC to use Swift PM

- projects.json
Add https://github.com/apple/swift-system
```
PASS: swift-system, 5.2, 0627d2, Swift Package
Passed: 1
Failed: 0
XFailed: 0
UPassed: 0
Total: 1
Total: 1
Result: PASS
--- swift-system checked successfully against Swift 5.2 ---
```
> Add swift-system

- projects.json
Add swift-log to the suite.
- 5.0+
```
PASS: swift-log, 5.2, 16cfcc, Swift Package
Passed: 1
Failed: 0
XFailed: 0
UPassed: 0
Total: 1
Total: 1
Result: PASS
--- swift-log checked successfully against Swift 5.2 ---
```
> add swift-log

- projects.json
Adds swift metrics 
- 5.0+
```
$ /Users/ktoso/code/swift-source-compat-suite/runner.py --swift-branch swift-5.2-branch --swiftc /usr/bin/swiftc --projects /Users/ktoso/code/swift-source-compat-suite/projects.json --include-repos 'path == "swift-metrics"' --include-versions 'version == "5.2"' --include-actions 'action.startswith("Build")'
PASS: swift-metrics, 5.2, 68e6cb, Swift Package
Passed: 1
Failed: 0
XFailed: 0
UPassed: 0
Total: 1
Total: 1
Result: PASS
--- swift-metrics checked successfully against Swift 5.2 …
```
> add metrics

- projects.json
Add https://github.com/apple/swift-argument-parser
```
PASS: swift-argument-parser, 5.2, 41f5fe, Swift Package
Passed: 1
Failed: 0
XFailed: 0
UPassed: 0
Total: 1
Total: 1
Result: PASS
--- swift-argument-parser checked successfully against Swift 5.2 ---
```
> Add swift-argument-parser

- projects.json
SwiftFormat is a code library and command-line tool for reformatting Swift code on macOS or Linux.
* MIT
> Add SwiftFormat

- projects.json
add async http client
- 5.0+
```
PASS: async-http-client, 5.2, a72c5a, Swift Package
Passed: 1
Failed: 0
XFailed: 0
UPassed: 0
Total: 1
Total: 1
Result: PASS
--- async-http-client checked successfully against Swift 5.2 ---
```
> add async http client

- projects.json
adds distributed tracing repo.
Important to run both 5.0 and 5.2 since the project has a bunch of features only available on 5.2
- 5.0+
```
PASS: swift-distributed-tracing, 5.2, 73f2b5, Swift Package
Passed: 1
Failed: 0
XFailed: 0
UPassed: 0
Total: 1
Total: 1
Result: PASS
--- swift-distributed-tracing checked successfully against Swift 5.2 ---
```
> add distributed tracing

- projects.json
add swift cluster membership
- 5.2+ AFAIR
```
PASS: swift-cluster-membership, 5.2, 0fd434, Swift Package
Passed: 1
Failed: 0
XFailed: 0
UPassed: 0
Total: 1
Total: 1
Result: PASS
--- swift-cluster-membership checked successfully against Swift 5.2 ---
```
> add swift cluster membership

- projects.json
Add https://github.com/apple/swift-atomics
```
PASS: swift-atomics, 5.2, df9f81, Swift Package
Passed: 1
Failed: 0
XFailed: 0
UPassed: 0
Total: 1
Total: 1
Result: PASS
--- swift-atomics checked successfully against Swift 5.2 ---
```
> Add swift-atomics

- common.py
[swift-crypto v1.1.4](https://github.com/apple/swift-crypto/releases/tag/1.1.4) has all the changes we need and we can pin to that version instead of `main`.
> Pin swift-crypto to a version

- common.py
[v1.1.5](https://github.com/apple/swift-crypto/releases/tag/1.1.5) contains a fix for cmake build on aarch64
> Update swift-crypto to 1.1.5

- run_sk_stress_test
- sourcekit-xfails.json
Also only build x86_64 for generic/macOS actions. Doing arm64 as well doesn't make much difference to SourceKit and adds a bunch of time.
> [run_sk_stress_test] Update stress test xfails.

- projects.json
Add [Eureka](https://github.com/xmartlabs/Eureka) project to projects.json
- extensive use of generics which has been broken several times in the past when a new Swift/Xcode version is released
* BSD
* MIT
* MPL 2.0
* CDDL
> Add Eureka project

- sourcekit-xfails.json
> Remove SR-14318 and SR-14319 from SourceKit Stress Tester XFAILs

- checkout
`project` has been renamed to `project_future` in 51e08a09ae2b69b219575490da5849793cfa8304. 
Currently the `checkout` script fails when run.
> Fix bug in checkout script

- sourcekit-xfails.json
SR-14317 has been fixed in https://github.com/apple/swift/pull/36582.
> Remove SR-14317 from Stress Tester xfails

- CODEOWNERS
Hopefully, this will mean that I don’t have to bother @clackary or @shahmishal for changing the Stress Tester’s XFails file.
> Add myself as code owner for sourcekit-xfails.json

- run_sk_stress_test
If the file covered by an XFail is not tested in the current run, it appears neither in the expected failures, nor in the unexpected failures section.
List these XFails their own section. I deliberately chose not to fail the stress tester if we have one of these XFails because
a) files also end up here if their project isn’t run in the current stress tester run (might be interesting if we include more projects in the weekly run again)
b) the XFail is still valid but it’s shadowed by a different failure which causes the stress tester to not reach the XFailed file
If neither of these reasons applies, we can remove an XFail.
> [Stress Tester] Report XFails whose file was not tested in the current run

- project_future.py
```
error: could not write driver dependency graph
```
> Add disable-incremental-imports flag to workaround debug failure

- sourcekit-xfails.json
- Remove whose issue is fixed and that are not processed during the stress tester run
- Clean up path of new XFails to use `*` whitespace for the path to `project_cache`
> Update SourceKit XFails

- project_precommit_check
Allow the use of the 5.3 compiler in precommit checks.
> project_precommit_check: Add 5.3 as a supported configuration

- projects.json
Add the recently announced [Swift Collections][swift-collections] and [Swift Collections Benchmark][swift-collections-benchmark] packages to the source compatibility suite.
[swift-collections]: https://github.com/apple/swift-collections
[swift-collections-benchmark]: https://github.com/apple/swift-collections-benchmark
Note: This requires #508 for the precommit check to pass.
* BSD
* MIT
* **Apache License, version 2.0**
* MPL 2.0
* CDDL
```shellsession
$ swiftc --version
Apple Swift version 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28)
Target: x86_64-apple-darwin20.4.0
$ …
```
> Add swift-collections and swift-collections-benchmark

- sourcekit-xfails.json
- https://bugs.swift.org/browse/SR-14498 has been fixed
- Found a new issue that already has a PR fixing it, up
> [Stress Tester XFAils] Update XFails

- projects.json
This is a fix for #527 
It now succeeds as below:
```
$ /Users/onevcat/Desktop/swift-source-compat-suite/runner.py --swift-branch swift-5.1-branch --swiftc /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc --projects /Users/onevcat/Desktop/swift-source-compat-suite/projects.json --include-repos 'path == "Kingfisher"' --include-versions 'version == "5.1"' --include-actions 'action.startswith("Build")'
$ git -C /Users/onevcat/Desktop/swift-source-compat-suite/project_cache/Kingfisher rev-parse --show-toplevel
PASS: Kingfisher, 5.1, 44450a, Kingfisher, generic/platform=iOS
$ git -C /Users/onevcat/Desktop/swift-source-compat-suite/project_cache/Kingfisher rev-parse --show-toplevel
PASS: Kingfisher, 5.1, 44450a, …
```
> Fix Kingfisher build by the new scheme settings

- sourcekit-xfails.json
- SR-14328 has been resolved
- SR-14544, SR-14546, SR-14547 are new issues previously shadowed by other failures
- SR-14545 is a different path that hits the same assertion as SR-14495
> [Stress Tester XFails] Remove SR-14328, add SR-14544, SR-14545, SR-14546, SR-14547

- sourcekit-xfails.json
Add XFail another case of SR-14544 that was previously hidden by other XFail and re-add SR-14618, which wasn’t actually fixed.
> [SourceKit XFails] Update XFails

- projects.json
Add project [Doggie](https://github.com/SusanDoggie/Doggie)
* BSD
* **MIT**
* MPL 2.0
* CDDL
```
./project_precommit_check Doggie  --earliest-compatible-swift-version 5.3
** CHECK **
--- Validating Doggie Swift version 5.3 compatibility ---
--- Project configured to be compatible with Swift 5.3 ---
--- Checking Doggie platform compatibility with Darwin ---
$ …
```
> Add Doggie

- analyze_request_durations.py
- run_sk_stress_test
Depends on https://github.com/apple/swift-stress-tester/pull/150
-----------------
Use the new capability of the stress tester to measure the time it took to execute code completion requests, gather that information and report an analysis on how long all code completion requests that were executed during the stress tester run took.
This should allow us to verify changes to code completion don’t introduce significant regressions and will hopefully give us a way to find situations in which code completion is slower than it should be.
-------------------
It looks like CI isn’t able to pick up this change as a related PR to my changes in the main Swift or the stress tester repo, so I can’t run it and see what the final results look like in CI. Instead, here’s a short teaser of what I got from …
> [Stress Tester] Use new duration measurement capability of stress tester to analyse code completion durations

- projects.json
This fails the same way as https://bugs.swift.org/browse/SR-14655
Work arounds rdar://81276100
> XFAIL RxTest on release/5.5 as well

- projects.json
This project is also failing on the `release/5.5` branch: https://ci.swift.org/job/swift-5.5-source-compat-suite/104/console
> XFAIL swift-distributed-tracing on release/5.5.

- projects.json
These projects are failing in the source compatibility suite for the `release/5.5` branch: https://ci.swift.org/job/swift-5.5-source-compat-suite//112/console
> XFAIL a couple projects on release/5.5.

- projects.json
Main should be good again.
Undoes https://github.com/apple/swift-source-compat-suite/pull/571
We require 5.2+ nowadays.
FYI @hborla @slashmo
> Re-enable distributed tracing main branch

- project_future.py
fix logical should 'not in' and fixed function must one space
* MIT
@swift-ci Please test source compatibility
> minor fixing: logical, and function issue lint

- projects.json
Add the mqtt-nio package to the source compatibility suite.
* BSD
* **MIT**
* MPL 2.0
* CDDL
```console
$ ./project_precommit_check --earliest-compatible-swift-version 5.1 mqtt-nio
** CHECK **
--- Validating mqtt-nio Swift version 5.1 compatibility ---
--- Project configured to be compatible with Swift 5.1 ---
--- Checking mqtt-nio platform compatibility with Darwin ---
$ …
```
> Add mqtt-nio

- run_sk_stress_test
I mistakingly removed the raw output in https://github.com/apple/swift-source-compat-suite/pull/578 as well, but I only meant to remove the processed output.
> Print raw request durations after running the SourceKit stress tester

- projects.json
Hello, this pull request adds compatibility check for GRDB 5.9.0 and Swift 5.3.
* BSD
* MIT
* MPL 2.0
* CDDL
```
$ ./project_precommit_check GRDB.swift --earliest-compatible-swift-version 5.3
** CHECK **
--- Validating GRDB.swift Swift version 5.3 compatibility ---
--- Project configured to be compatible with Swift 5.3 ---
--- Checking GRDB.swift platform compatibility with Darwin ---
$ /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc …
```
> Update GRDB.swift for Swift 5.3

- projects.json
underlying issue was addressed in https://github.com/apple/swift-package-manager/pull/3713
> remove xfail from kitura 5.1

- projects.json
* Swift 4
* Swift 4.2
* Swift 5
Avoid building the same SHA for multiple Swift 5.x version.
> Swift Version flag (-swift-version) supports

- run_sk_stress_test
Useful to reproduce stress tester failures of a single project locally.
> Add an option to only stress test a single project

- projects.json
Fixed by a change to swiftpm.
rdar://83452858
> Remove XFAIL for swift-nio-ssl

- projects.json
We're still seeing the failure on 5.5. XFAIL for now.
> XFAIL swift-nio-ssl only on release/5.5

- build_incremental.py
- project_future.py
- projects.json
- run_sk_stress_test
- runner.py
Currently we’re in a state again in which some project succeed to build in the stress tester CI job but fail to build in the source compatibility suite CI job (rdar://82333521). We are thus mistakingly receiving UPASSes in the stress tester CI job.
To work around this, introduce the notion of job types to the source compatibility runner and its associated XFails. By default everything runs as the "source-compat" job, only the stress tester overrides the job to "stress-tester". That way we can selectively XFail jobs only for the stress tester in `projects.json`.
Since the stress tester now controls its own project build XFails, a project build failure will also cause a stress tester failure.
rdar://62080167
> Manage the project XFails under a different job type for the stress tester

- projects.json
This patch updates swift-nio-ssl and removes the xfail annotation introduced in #602.
> Use a more recent swift-nio-ssl

- projects.json
One of SwiftLint's dependencies is SWXMLHash. In versions of
that package prior to its 5.0.0 release, the XMLParser type
was imported from Foundation. But, that type has since moved
on Linux platforms to the FoundationXML module. This leads to
build failures such as:
```
swift-source-compat-suite/project_cache/SwiftLint/.build/
checkouts/SWXMLHash/Source/SWXMLHash.swift:296:38: error:
'XMLParser' is unavailable: This type has moved to the
FoundationXML module. Import that module to use it.
func parser(_ parser: Foundation.XMLParser,
^~~~~~~~~
```
SwiftLint updated its dependency on SWXMLHash to be >= 5.0.0
in [f5174b316878793e4c24b63741459c1b852f480b](https://github.com/realm/SwiftLint/blob/f5174b316878793e4c24b63741459c1b852f480b/Package.resolved), which happened
on Oct 8th, 2019, a …
> Split-off versions of SwiftLint that no longer compile on Linux

- README.md
As suggested here: https://github.com/apple/swift-source-compat-suite/pull/599#issuecomment-932502053
> Add README entry how to only XFail the Source Comapat CI job

- projects.json
This updates the swift-nio-ssl 5.0 version to the last release that supported that far back in order to fix rdar://83865752.
> Update the old nio-ssl version to work around the compiler

- project_future.py
- run
- runner.py
'--clang' provides a way to build projects with a custom clang binary.
With '--clang-source-path', the 'run' script builds clang binary from
the clang source in the path and provides this binary path to 'runner.py'
using the '--clang' flag.
* BSD
* MIT
* MPL 2.0
* CDDL
> Add '--clang' flag to runner.py

- projects.json
Before #613 the SourceKit stress tester was using the 5.1 version of Result and had XFails that matched the source offset of that version of the library. Use the commit hash that was previously used for 5.1 for Swift 5.0.
> Add a Swift 5.0 version of Result

- projects.json
Add https://github.com/abertelrud/swift-protobuf-plugin-example.git to the source compatibility suite.
This is a test of SwiftPM functionality that is new in SwiftPM 5.6.  Since the compatibility versions use Swift language versions and not Swift toolchain versions, it was suggested to use an XFAIL for the `release/5.5` branch.
This is a sample package that uses a modified version of swift-protobuf to which a SwiftPM build tool plugin has been added.  The sample verifies that `.proto` files get processed properly.
This is currently only Darwin but a future PR will extend it to Linux.
rdar://84315022
> Add swift-protobuf-plugin-example to test SwiftPM build tool plugin functionality

- projects.json
Add an entry for the standard library preview repository.
On Linux, the project requires the --enable-test-discovery flag to be passed in order to build on Swift 5.1 through 5.3.
I don't know where to add this.
This project supports Swift 5.1 and up; there is no Swift 4.0 branch.
* BSD
* MIT
* MPL 2.0
* CDDL
> add entry for the standard library preview repository

- project_future.py
- run_sk_stress_test
- runner.py
Previously, when running the stress tester, we changed the `swiftc` propertie in `project_future.py` to `sk-swiftc-wrapper`. But this only worked if `sk-swiftc-wrapper` is installed into the toolchain because it tries to find `swift` next to it.
To support using an `sk-swiftc-wrapper` that’s not installed into the toolchain, keep the `swiftc` property pointing to the actual `swiftc` executable in the toolchain and add a new option with which we override the `SWIFT_EXEC` that is actually used to build the projects to `sk-swiftc-wrapper`.
> Support using `sk-swiftc-wrapper` that is not installed in the toolchain

- projects.json
The following tests are failing on Ubuntu with tools built from
release/5.6 and main.
https://ci.swift.org/job/swift-5.6-source-compat-suite-ubuntu-2004/1/
https://ci.swift.org/view/Source%20Compatibility/job/swift-source-compat-suite-ubuntu-2004/111/
```
Failures:
FAIL: AsyncNinja, 5.0, 7bd7ea, Swift Package
FAIL: Kitura, 5.0, 8578c4, Swift Package
FAIL: Kitura, 4.0, f1c316, Swift Package
FAIL: Perfect, 4.2, cdc17d, Swift Package
FAIL: SwiftLint, 5.0, 180d94, Swift Package
```
> [XFail] Xfailed projects failing on linux.

- run_sk_stress_test
I just realized `--filter-by-project` is using the same metavar as `--filter-by-tag`. Most likely a copy-paste error.
> Use different metavar for `--filter-by-project` instead of `--filter-by-tag` in run_sk_stress_test

- project_future.py
`-C` has been deprecated in favor of `--package-path`
> Use --package-path instead of -C when building SwiftPM packages

- run_sk_stress_test
This should speed up the stress tester run if it can use cached compile products when building the Swift toolchain.
> Support using sccache when building the Swift toolchain for a stress tester run

- projects.json
This marks the swift-protobuf-plugin-example test as XFAIL.  There seems to be a bug in which SwiftPM is no longer respecting `--disable-sandbox` for plugins, and this nesting of sandboxes causes the invocation of the package plugin to fail.
> Mark swift-protobuf-plugin-example as XFAIL until rdar://90955872 is fixed

- projects.json
SwiftPM has now been fixed.
This reverts commit 0c90004734822014a6bc44b8694b36d904b73eae.
> Revert "Mark swift-protobuf-plugin-example as XFAIL until rdar://90955872 is fixed"

- projects.json
Now that https://bugs.swift.org/browse/SR-13190 is fixed we get UPASS for the SRP package, so we should remove the XFAIL for main.
> Un-XFAIL SRP on main now that SR-13190 is fixed

- common.py
https://github.com/apple/swift/pull/40188 started building the Swift compiler with the `gfm` branch of swift-cmark, but the source-compat suite needs to be updated separately to point to that branch. This PR does that update.
> use swift-cmark/gfm for testing main

- projects.json
Adding [Violet - Python VM written in Swift](https://github.com/LiarPrincess/Violet).
Swift Package Manager
Tested on:
- macOS
- Intel
- 11.6.2 (BigSur) + Xcode 12.4 (Swift 5.3.2)
- 11.6.2 (BigSur) + Xcode 13.0 (Swift 5.5)
- Apple
- ⚠️ Not tested! I don't have M1. ⚠️
- Ubuntu
- 21.04 + Swift 5.4.2 - use `make test` and `make pytest`
- Docker
- `swift:latest` (5.6.0) - use `make docker-test` and `make docker-pytest`
- `swift:5.3.2` - use `make docker-test-old` and `make docker-pytest-old`
No Swift 4.0 support, although from what I see there are some other projects (like [apple/swift-argument-parser](https://github.com/apple/swift-argument-parser)) that only support 5+.
Our target in `project_precommit_check`: …
> Added Violet - Python VM written in Swift

- projects.json
Version `1.11.1` of `AsyncHTTPClient` only supports Swift 5.4+
https://github.com/swift-server/async-http-client/releases/tag/1.11.1
rdar://94044142
> Update `AsyncHTTPClient` to latest version `1.11.1`

- build_incremental.py
- builder.py
- checkout
- cleanup
- common.py
- project.py
- project_precommit_check
- reproduce.py
- run
- run_cperf
- run_sk_stress_test
- runner.py
- utils/format_projects_list.py
Updated all Python scrips in the repository to support Python3 and dropped support for Python2. This included
* Fixing syntax errors throughout
* Using pythonic context managers to handle file management
* Using a proper `Enum` class for results handling
* Cleaning imports and updating shebang lines
I also took it upon myself to rename `project_future.py` -> `project.py` as we originally intended
Not applicable here
> Migrate from Python2 to Python3

- run_sk_stress_test
- Open files that should be parsed as JSON as normal (non-binary) files
- Revert https://github.com/apple/swift-source-compat-suite/pull/345 because it was causing issues. Maybe the underlying issue is fixed in Python3. At least I haven’t been able to reproduce it 🤷 
- While doing this, I also added a few type hints to the Python script.
> Fix Python3 issues and add type hints to run_sk_stress_test

- run_sk_stress_test
I only discovered these when running with Python 3.9 (they passed with Python 3.8).
> Fix more Python 3 issues in run_sk_stress_test

- projects.json
```
error: the Swift tools version specification is missing a label; consider inserting 'swift-tools-version:' between the comment marker and the version specifier
```
> Disable SRP on release/5.7

- project.py
Fix issue with project building with armv7/armv7s
```
<unknown>:0: error: could not find module '_StringProcessing' for target 'armv7-apple-ios'; found: arm64e-apple-ios, arm64-apple-ios, at: /Users/ec2-user/jenkins/workspace-private/swift-main-source-compat-suite/build/compat_macos/install/toolchain/usr/lib/swift/iphoneos/_StringProcessing.swiftmodule
```
This started failing after https://github.com/apple/swift/pull/60363 (Dropping support for armv7/armv7s from iOS platform)
> Exclude armv7 and armv7s from iOS platform

- projects.json
We now skip armv7 and armv7s architecture (#688)
These projects only failed before for those specified architectures. This PR removes those xfails to prevent unexpected passes from occuring. 
Failing builds seen here:
https://ci.swift.org/job/swift-PR-source-compat-suite-test-macOS/38/
https://ci.swift.org/job/swift-PR-source-compat-suite-test-macOS/37/console
Verified locally that the `UPASS`'s no longer appear with this change
> [Hotfix] Un-xfail Kingfisher and ReactiveKit after #688

- build_incremental.py
- builder.py
- project.py
- runner.py
Parallelize project builds to speed up testing time significantly
As part of this PR
* Converted the factory pattern to use a `FactoryBuilder` object for handling object instantioation. This allows the factory pattern to be pickle-able which is required for multiprocessing support
* Implemented the `ProjectListBuilder.build()` function in order to parallelize the project builds across the desired number of processes
* Cleaned up some of the `XcodeTarget` logic which was printing various messages to stdout when it should have been printing to the log files. This became increasingly obvious/annoying after adding multiprocessing support
Previously we had a factory which basically encapsulated certain constructor args with a lambda. However, this is un-pickable from python standards which …
> Parallelize project builds

- README.md
- build_incremental.py
- builder.py
- checkout
- cleanup
- common.py
- project.py
- project_precommit_check
- reproduce.py
- run
- run_cperf
- run_sk_stress_test
- runner.py
- utils/format_projects_list.py
* Drop a note in the readme about Python 3.8 support as a result from #681
* Update recently touched files to bump the copyright to 2022 (A result from #681 and #687)
This is a non-functional change and does not affect any logic in the codebase
> [NFC] Update readme & copyrights

- run_sk_stress_test
Stress testing a single project already utilises the CPU 100% and stress testing multiple causes timeouts.
> Don’t build multiple project in parallel while stress testing

- projects.json
This project should be fixed by https://github.com/apple/swift/pull/60008 and https://github.com/apple/swift-numerics/pull/233.
Reverts apple/swift-source-compat-suite#678
> Re-enable swift-numerics

- project.py
If we invoke `project_subbilder.build()` immediately on the subprocess, it gets a fresh set of global variables and thus also uses the standard default timeout of 10 minutes, ignoring any timeout that was specified using `--default-timeout`. And 10 minutes is not enough to stress test a project.
> Pass the default process timeout from the main process to the subprocesses that build the projects

- project.py
With the introduction of `start_process` from #693 , we just need to return the results accordingly from the function so they can be processed correctly.
Currently the function returns `None` since there is no return value
> [Hotfix] Return results accordingly from the spawned process

- projects.json
This resolves errors with expired certs in the tests.
> Update swift-nio-ssl to latest HEAD.

- cleanup
- common.py
This is similar to https://github.com/apple/swift/pull/60193.
> Checkout Swift LLVM Bindings repo

- projects.json
Add [BricBrac](http://github.com/glimpseio/BricBrac)
* BSD
* **MIT**
* MPL 2.0
* CDDL
```
marc@bix swift-source-compat-suite % ./project_precommit_check BricBrac --earliest-compatible-swift-version 5.3
** CHECK **
--- Validating BricBrac Swift version 5.3 compatibility ---
--- Project configured to be compatible with Swift 5.3 ---
--- Checking BricBrac platform compatibility with Darwin ---
$ …
```
> Add BricBrac

- projects.json
* Xfail ACHNBrowserUI which started failing after the LLVM branch update. 
Currently failing job: https://ci.swift.org/job/swift-main-sourcekitd-stress-tester/177/
> Xfail ACHNBrowserUI

- projects.json
* Updarte Xfail https://github.com/apple/swift/issues/60627 from Doggie. 
This compiler crash does not occur when building the project in debug
> Update Doggie xfail https://github.com/apple/swift/issues/60627

- project.py
- runner.py
Added JUNIT functionality to the `ProjectListResult` so users of `runner.py` can generate Junit results as needed. This will make CI jobs much easier to reason through and make identifying failures much easier.
* Updated Results objects to contain a link to their build log if it exists
* Added Junit functionality to `ProjectListResult`. Each junit test case simply adds a link to the jenkins artifact in the stdout. This will save XML space significantly
* Wrapped JUINT functionality behind `--junit` flag. No current consumers of the project will see changes until they pass the `--junit` flag appropriately
> Add option to generate JUNIT reslts

- project.py
For reasons I don’t fully understand `subbuilder_result` can be `None`, so we can’t assign the `logfile` property here. This caused the stress tester to fail with the following error: (https://ci.swift.org/job/swift-main-sourcekitd-stress-tester/191/console)
```
Traceback (most recent call last):
File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/process.py", line 243, in _process_worker
r = call_item.fn(*call_item.args, **call_item.kwargs)
File "/Users/ec2-user/jenkins/workspace/swift-main-sourcekitd-stress-tester/swift-source-compat-suite/project.py", line 1052, in start_process
return project_subbuilder.build()
File "/Users/ec2-user/jenkins/workspace/swift-main-sourcekitd-stress-tester/swift-source-compat-suite/project.py", …
```
> Fix a Python exception that occurred while running the SourceKit stress tester

- run
* Add the ability to invoke main.py with the `--junit` flag. This will allow us to generate junit for CI jobs
> Enable --junit to run.py for PR's

- common.py
* Fix compiler builds on main after  [f9cff13604edcfe196f4db6969d97803c15506a8](https://github.com/apple/swift/commit/f9cff13604edcfe196f4db6969d97803c15506a8)
> add swift syntax to checkouts

- cleanup
* Remove swift-syntax from build directory.
Will fix https://ci.swift.org/job/swift-main-sourcekitd-stress-tester/198/
> remove swift syntax directory

- run_sk_stress_test
* Remove unnecessary git clone now that swift-syntax is cloned by default as part of the compiler builds.
Now that swift-syntax is cloned by default when building the main branch, we don't need to clone it again. This should fix the  clone errors seen here: https://ci.swift.org/job/swift-main-sourcekitd-stress-tester/199
For reference: https://github.com/apple/swift-source-compat-suite/pull/715
> [stress-tester] Don't clone swift syntax on main

- projects.json
* Remove xfail for compiler crash on linux. The fix was landed here: https://github.com/apple/swift/pull/60902
Will close the associated swift issue once this is merged.
I've verified the issue is fixed with the newest `swiftlang/swift:nightly-focal` docker image. You can see the project UPASSing here on CI: https://ci.swift.org/job/swift-source-compat-suite-ubuntu-2004/56/testReport/junit/(root)/build/_Doggie__5_0__965946__Swift_Package/
> Remove linux based xfail for Doggie after compiler fix

- run_cperf
* Fix cperf writing strings to a file, not bytes
This popped up after we recently updated the compiler performance jobs to use python3.
https://ci.swift.org/job/swift-PR-compiler-performance-macOS/42/
> Write regular strings to file

- projects.json
Reverts apple/swift-source-compat-suite#731
Looks like sandboxing issue has been fixed and project is now UPASS'ing.
> Revert "Xfail swift-protobuf-plugin-example on main"

- sourcekit-xfails.json
`ACHNBrowserUI/extensions/Path.swift` has wildly different run times depending on the run. The stress tester has now been updated to always give it a soft timeout (ffb5a01e22683b0a1419b6fd775bb45af50660fb). Add the xfail back in.
> Add flaky ACHNBrowserUI timeout

- projects.json
This should restore testing of SRP against Swift 5. I haven't tested this locally as I don't have access to a properly configured system. I might need to raise the tools version as my `Package.swift` specifies `swift-tools-version:5.1`. 
I've removed supported Swift 4.0 a long time ago, so I've removed it from the manifest.
> Update SRP to test latest version and drop Swift 4

- projects.json
This reverts commit 22bfd967876051b363cc76461ca5521c3f8de189.
The issue was resolved: https://github.com/apple/swift/issues/61905
> Revert "xfail CoresStore https://github.com/apple/swift/issues/61905"

- common.py
This version bump would benefit SwiftPM, Swift Driver, and SourceKit-LSP, which all use ArgumentParser.
> common.py: update ArgumentParser to 1.2.0

- common.py
This fixes an issue resolved in jpsim/Yams#353, which is currently blocking apple/swift-package-manager#5894.
> common.py: bump Yams to 5.0.1

- common.py
This PR is accompanied by https://github.com/apple/swift/pull/59009 https://github.com/apple/swift-driver/pull/1218 https://github.com/apple/swift-package-manager/pull/5884 https://github.com/apple/sourcekit-lsp/pull/673 and should be merged synchronously with those.
> Bump `swift-argument-parser` to 1.1.4

- projects.json
The Git URL of Evergreen (https://github.com/brentsimmons/Evergreen.git) no longer exists, it redirects to NetNewsWire. This is causing failures in CI during clone ([swift-main-source-compat-suite-debug](https://ci.swift.org/job/swift-main-source-compat-suite-debug/307/)). 
Since the project has also been renamed and there is no longer an Xcode workspace, I’m not sure if they are the same projects. If NetNewsWire should be part of the source compat suite, it should be added again.
> Remove Evergreen

- projects.json
Reverts apple/swift-source-compat-suite#759
Should have been fixed by https://github.com/apple/swift/pull/63266.
> Revert "Xfail rxswift https://github.com/apple/swift/issues/63242"

- project_precommit_check
- projects.json
Now that swift 5.7 is stable we really should be testing the distributed actors cluster because it is the large codebase pushing both swift concurrency and the distributed feature.
https://github.com/apple/swift-distributed-actors
This requires 5.7 so we need to add that Swuft support... not entirely sure how to do that, will reach out to someone.
- it uses language features which require 5.7, so that's the minimum version
- TODO
> +add Distributed Actors

- common.py
* Fix build issue due to mismatched LLVM version, `stable/20220421` does not contain the LLVM cmake function `llvm_add_tool_symlink` causing builds to fail.
* Fix builds on all branches != `main` after [`b933299efa73fa3ecf78f7b2d5769596b3a66fe6`](https://github.com/apple/swift-source-compat-suite/commit/b933299efa73fa3ecf78f7b2d5769596b3a66fe6)
On any branches which don't need to clone `swift-asn1` and `swift-certificates` the build shouldn't clone those branches
> Fix source compat swift builds

- projects.json
Resolves rdar://106086239
Related issue to rework the testkit: https://github.com/apple/swift-distributed-actors/issues/1113 
We can't `swift build -c release` the testkit target, it is only used in testing though. Potentially we could remove it entirely now that Swift gained async await and actors, but that's a large piece of work.
> xfail distributed cluster on release builds; we use @testable for teskit

- projects.json
swift-nio only encounters a compiler crash when building the release config with --build-tests, which was recently removed in favor of only building tests in debug configs.
The issue is still real, so I will leave the associated swift issue open
> unxfail swift-nio after --build-tests removed from release builds

- projects.json
* Mistakenly removed this xfail as it passed locally (arm). This still fails in CI, the xfail should remain
> xfail swift-cluster-membership (debug) - fails with x86_64

- run_sk_stress_test
Tests are only built when the project is built in debug config and to get test coverage for those as well, we should be building for debug when running the stress tester.
> Build projects in debug config when stress testing

- projects.json
Adds both Graphiti and GraphQL projects to the suite.
* MIT
Graphiti
```
PASS: Graphiti, 5.0, 64b180, Swift Package
Passed: 1
Failed: 0
XFailed: 0
UPassed: 0
Total: 1
Total: 1
Result: PASS
--- Graphiti checked successfully against Swift 5.0 ---
```
GraphQL
```
PASS: GraphQL, 5.0, 7c910f, Swift Package
Passed: 1
Failed: 0
XFailed: 0
UPassed: 0
Total: 1 …
```
> Add Graphiti and GraphQL projects

- projects.json
Adds Smtp project to the suite - https://github.com/Mikroservices/Smtp.
Note that a recent compiler regression was discovered when building this project in release mode. https://github.com/apple/swift/issues/64219
* MIT
```
PASS: Smtp, 5.0, e8f09e, Swift Package
Passed: 1
Failed: 0
XFailed: 0
UPassed: 0
Total: 1
Total: 1
Result: PASS
```
> Add Smtp project

- projects.json
Hello, this pull request adds compatibility check for GRDB with Swift 5.0, 5.1, 5.3, and 5.7.
Compatibility with Swift 5.3 had been added by #574, but it was reverted for some reason (???). This PR restores the deleted compatibility checks.
* BSD
* MIT
* MPL 2.0
* CDDL
```
$ ./project_precommit_check GRDB.swift --earliest-compatible-swift-version 5.7
** CHECK **
--- Validating GRDB.swift Swift version 5.7 compatibility ---
--- Project configured to be compatible with Swift 5.7 ---
--- Checking GRDB.swift platform compatibility with Darwin --- …
```
> Add GRDB+Swift 5.7

- projects.json
This test is still failing in CI when testing PRs. 
See https://github.com/apple/swift/issues/65011
https://ci.swift.org/job/swift-PR-source-compat-suite-test-macOS/178/
> Re-disable swift-distributed-actors

- project.py
- projects.json
* Add ability to build release configuration of a swift package with `--build-tests` by adding `build_tests_release` to the project configuration
There are projects which are edge cases which need to be able to build even the release configurations of their swift package with `--build-tests` in order to build correctly.  swift-distributed-actors is such a project. By default we only build tests with the debug config of a project, but this gives project owners the ability to override that and force test builds with release config
> Add ability to build tests with release configs

- run_sk_stress_test
`sk-swiftc-wrapper` wraps `swiftc` but if we enable the integrated driver, `swiftc` is not getting called, so there’s nothing to wrap. Until we update the stress tester to wrap `swift-frontend`, disable the integrated driver.
> Disable integrated driver for SourceKit stress tester

- run_sk_stress_test
Depends on https://github.com/apple/swift/pull/65706
---
The hard-coded `build-script` invocation is gross and also didn’t build the new driver, which lead to issues. Use a preset based on the source compat suite presets instead.
Effectively, this will add the following arguments to the `build-script` invocation. `--llvm-install-components` and `--swift-install-components` just show the components the newly added components.
```
--cross-compile-hosts=macosx-arm64
--install-llvm \
--install-swift-driver \
--llvm-install-components=clang;clang-resource-headers;compiler-rt;clang-features-file
--swift-driver \
--swift-install-components=back-deployment;libexec
```
> Use a preset for the build-script invocation used by `run_sk_stress_test`

- projects.json
Add [Swift Power Assert](https://github.com/kishikawakatsumi/swift-power-assert) project.
* BSD
* MIT
* MPL 2.0
* CDDL
> Add Swift Power Assert project

- sourcekit-xfails.json
This should get the 5.9 stress tester job into a state where we can actually look at the differences between `main` and `release/5.9` and decide how to handle them.
And while at it, remove the XFails for 5.8 because the 5.8 stress tester job no longer runs.
> [Stress tester XFails] Mark all XFails in `main` as XFails in `release/5.9`

- projects.json
Update xfails to fix 5.8 jobs.
swift-power-assert only supports 5.9+
https://github.com/kishikawakatsumi/swift-power-assert/blob/main/Package.swift#L1
> [Xfail] swift-power-assert only supports 5.9+

- projects.json
Reverts apple/swift-source-compat-suite#830
Fixed with https://github.com/apple/swift-package-manager/pull/6723 , this will prevent the project UPASSing
> Revert "[Xfail] swift-power-assert for a linking failure"

- projects.json
The current pinned version does not contain `Predicate` variadic generics, which is an area we are seeing a lot of the compact issues. Let's update the version to include that (introduced with https://github.com/apple/swift-foundation/pull/178).
This commit has been tested [here](https://github.com/apple/swift-foundation/pull/199). It passed both macOS and Linux tests.
> Update SwiftFoundation to include Predicate variadic generics support

- common.py
Update swift-argument-parser to 1.2.3.
* BSD
* MIT
* MPL 2.0
* CDDL
> Update the swift-argument-parser to 1.2.3

- project.py
* When we build swift packages, our timeout is 3600, we should match that with xcodebuilds. All our spurious timeouts are occurring on xcodebuilds because the previous default timeout isn't enough. Thus we se
`sandbox-exec: Timed out`
> make build timeout for xcodebuilds match swift packages

- common.py
- project.py
* Rather than set the xcodebuild timeout to 3600, set the `DEFAULT_EXECUTE_TIMEOUT` var to 3600, this way consumer scripts can use `common.set_default_execute_timeout()` and override the xcode timeout properly
> Fix xcodebuild timeouts in consumer scripts

- common.py
- run
- run_cperf
- run_sk_stress_test
* Use update-checkout to reduce work related to keeping swift dependencies up to date for compiler builds
This will allow us to have 1 location to update when dependency updates are needed, eliminating the need for PR's such as #799 or #796
> Use update-checkout to pull swift dependencies

- common.py
- run_cperf
* Fix Workspace bug in performance jobs after move to update_checkout
```
$ git -C /Users/ec2-user/jenkins/workspace-private/swift-PR-compiler-performance-macOS/main/new/swift fetch origin pull/69591/merge
fatal: cannot change to '/Users/ec2-user/jenkins/workspace-private/swift-PR-compiler-performance-macOS/main/new/swift': No such file or directory
WORKSPACE: /Users/ec2-user/jenkins/workspace/swift-PR-compiler-performance-macOS
Traceback (most recent call last):
File "/Users/ec2-user/jenkins/workspace/swift-PR-compiler-performance-macOS/swift-source-compat-suite/run_cperf", line 632, in <module>
sys.exit(main())
File "/Users/ec2-user/jenkins/workspace/swift-PR-compiler-performance-macOS/swift-source-compat-suite/run_cperf", line 117, in main
setup_workspace(instance, workspace, args) …
```
> Ensure cperf sets up custom workspaces correctly

- projects.json
Resolve 3 xfails for swift-testing which have now been resolved:
- apple/swift#69096
- apple/swift-testing#138
- apple/swift-testing#139
For context, these xfails were added in these two PRs:
- #851
- #857
I also updated the baseline commit of swift-testing since we landed a [workaround](https://github.com/apple/swift-testing/pull/125) for another Swift compiler issue.
Resolves rdar://116924612
> Remove resolved xfails for swift-testing

- projects.json
* Update some xfails after the CI update.
See:
* https://ci.swift.org/job/swift-main-source-compat-suite-debug/647/artifact/swift-source-compat-suite/
* https://ci.swift.org/view/Swift%205.9/job/swift-5.9-source-compat-suite-debug/202/artifact/swift-source-compat-suite/
> Update xfails after xcode update

- run_sk_stress_test
We need to disable the integrated driver so that we can continue hooking `sk-swiftc-wrapper` into the compilation process as the Swift compilation driver. With the integrated driver, Xcode will only spawn swift-frontend processes and those don’t help us because they get frontend arguments while sourcekitd requires compiler arguments.
> [SourceKit stress tester] Disable the integrated driver for Xcode projects

- projects.json
Result is currently XFailed in the source compat suite. Since the SourceKit stress tester doesn’t respect these XFails, remove it from the stress tester projects for now.
> Don’t test the Result project in the SourceKit stress tester

- projects.json
Add [Penny](https://github.com/vapor/penny-bot) to the source-compatibility list. Penny is Vapor's automation bot.
Penny is compatible with the latest swift changes and upcoming flags (sometimes experimental too) so can be valuable in that aspect (flags visible in [Package.swift](https://github.com/vapor/penny-bot/blob/6726c1f39e3b54936cb02fa4b45979b12e503c10/Package.swift)). 
Furthermore Penny is a project deployed on Linux environments (currently on amazonlinux2 Swift images), so can be used by the source compatibility team as a means to ensure latest Swift changes are compatible with real-world Server-Side Swift apps deployed on Linux and AWS.
* BSD
* MIT
* Eclipse Public …
> Add vapor/penny-bot

- projects.json
[The issue](https://github.com/apple/swift/issues/71423) has been fixed and the project is currently UPASS'ing in main configuration.
> Un-XFAIL penny-bot project on main branch

- project_precommit_check
- projects.json
We should add https://github.com/apple/swift-sdk-generator to detect regressions.
* BSD
* MIT
* MPL 2.0
* CDDL
The project passes all checks except Swift 4.0 support, since its minimum supported version is 5.9.
> Add Swift SDK Generator

- projects.json
A closing brace was left behind in https://github.com/apple/swift-source-compat-suite/pull/912 .
> Fix invalid JSON.

- projects.json
I recently landed a change to suppress warnings for remote clang targets in SwiftPM (https://github.com/apple/swift-package-manager/commit/7ba0eb629490a6db480ccb4da9468dc9db4e0187).
> Un-XFAIL RxReactiveObjC in 6.0 configuration

- projects.json
This fixes swift-sdk-generator compat suite failures.
* BSD
* MIT
* MPL 2.0
* CDDL
> Fix CI failures (swift-sdk-generator, penny-bot, swift-distributed-tracing)

- projects.json
This is currently failing, presumably due to a package visibility change:
```
swift-source-compat-suite/project_cache/penny-bot/Lambdas/GitHubAPI/GeneratedSources/Types.swift:1147:59: error: initializer 'init(per_page:page:)' is package and cannot be referenced from a default argument value
1145 |     package func pulls_list_files(
1146 |         path: Operations.pulls_list_files.Input.Path,
1147 |         query: Operations.pulls_list_files.Input.Query = .init(),
|                                                           `- error: initializer 'init(per_page:page:)' is package and cannot be referenced from a default argument value
1148 |         headers: Operations.pulls_list_files.Input.Headers = .init()
1149 |     ) async throws -> Operations.pulls_list_files.Output {
:
30245 | …
```
> Temporarily disable penny-bot while we investigate the failure

- project_precommit_check
- projects.json
Add Hummingbird server framework to compat list
* BSD
* MIT
* MPL 2.0
* CDDL
The project passes all checks except Swift 4.0 support, since its minimum supported version is 5.9.
> Add Hummingbird

- projects.json
rdar://127206143 is now resolved, but rdar://128941797 is causing the project to still fail. apple/swift#73976 + apple/swift#73997 will resolve this though.
> Update XFAIL for swift-distributed-actors

- projects.json
Reverts 5505952f5a42cea60a9137c10a68886d8930fa77.
>     Temporarily disable penny-bot while we investigate the failure
> 
>     This is currently failing, presumably due to a package visibility
>     change:
>     ```
>     swift-source-compat-suite/project_cache/penny-bot/Lambdas/GitHubAPI/GeneratedSources/Types.swift:1147:59: err>
>      1145 |     package func pulls_list_files(
>      1146 |         path: Operations.pulls_list_files.Input.Path,
>      1147 |         query: Operations.pulls_list_files.Input.Query = .init(),
>           |                                                           `- error: initializer 'init(per_page:page:)>
>      1148 |         headers: Operations.pulls_list_files.Input.Headers = .init()
>      1149 |     ) async throws -> …
```
> Re-enable penny-bot.

- projects.json
Now that it's part of the toolchain, this test is no longer needed.
> Remove test for swift-foundation.

- projects.json
Adds an action to test RxSwift on Linux.
* MIT
> chore: Add Linux testing action for RxSwift

- projects.json
https://github.com/swiftlang/swift/issues/75655 was fixed in https://github.com/vapor/sql-kit/pull/185. This new revision is the first release containing the fix.
> Update vapor/sql-kit revision

- projects.json
* Xfail vapor jwt on 5.10 due to swiftpm bug
> xfail vapor_jwt on 5.10 due to swiftPM bug

- runner.py
cleanup clang cache to prevent project build errors
> cleanup clang cache before firing off list builder

- README.md
Linux has been supported for a while now, updating the README.
https://ci.swift.org/job/swift-source-compat-suite-debug-ubuntu-2004/
https://ci.swift.org/job/swift-source-compat-suite-ubuntu-2004/
> Update README.md to support Linux

- projects.json
Type-checking performance issue is fixed by https://github.com/swiftlang/swift/pull/63585
> Un-XFAIL Doggie in debug configuration on main

- projects-cperf-smoketest.json
- updates the Kingfisher entry in the cperf configuration to try and fix the compiler performance smoketests
- the existing prior commit for this project [appears](https://github.com/search?q=repo%3Aonevcat%2FKingfisher+23ef6c73ee3bc12ee3940136aea54bd44a02e93e&type=commits) to not exist in the project
aims to resolve https://github.com/swiftlang/swift/issues/78654
> [chore]: update cperf Kingfisher entry to try and fix build

- projects.json
Update fails to account for the release/6.1 branch
> [wip] Update xfails release 6.1

- projects.json
https://github.com/swiftlang/swift/issues/78870 has been fixes on main and release/6.1 and the projects are currently UPASS'ing.
> Remove XFAILs from vapor_jwt and vapor_jwt-kit projects

- project.py
Updates the usage of `swift test` to use `--package-path` instead of the deprecated `-C`.
Resolves `Unknown option '-C'` errors when attempting to run TestSwiftPackage actions.
Also includes a minor refactor to prevent extraneous `swift package clean` debug output from printing. This was due to a difference in `clean_swift_package` arguments.
N/A -- no new project is being submitted for review
> fix: Use --package-path for test actions

- projects.json
The constraint solver performance changes are reverted via https://github.com/swiftlang/swift/pull/79128 which means that Doggie tests are going to fail again.
> XFAIL Doggie in Debug configuration on main branch

- project.py
This will prevent build issues like
```
error: missing required module 'SwiftShims
```
when the `clang-stat-cache` present in the
Xcode installed in CI comes from an LLVM older than the one used
to build Swift (and in turn used by the ClangImporter).
Addresses rdar://144053750
> Do not use stat cache in compatibility suite

- projects.json
Fix for #955 with Swift 6.1. Tested against `swift-6.1-DEVELOPMENT-SNAPSHOT-2025-02-10-a-ubuntu24.04`.
```swift
/build/swift-source-compat-suite/project_cache/violet/Sources/Compiler/Implementation/CompilerImpl+Expr.swift:14:31: error: 'Expression' is ambiguous for type lookup in this context
12 | extension CompilerImpl {
13 | 
14 |   internal func visit(_ node: Expression) throws {
|                               `- error: 'Expression' is ambiguous for type lookup in this context
15 |     self.setAppendLocation(node)
16 |     try node.accept(self)
```
```
➜  swift-source-compat-suite git:(main) ✗ ./runner.py \
--swift-branch main \
--projects projects.json \
--include-actions 'action.startswith("Build")' \
--include-repos 'path == "violet"' \
--swiftc …
```
> [Violet] Fix for Swift 6.1 compatibility with `Foundation.Expression`.

- projects.json
Hello, this pull request adds compatibility check for GRDB with Swift 6.0.
* BSD
* MIT
* MPL 2.0
* CDDL
The last check does not pass, due to the lack of support for Swift 6.0 in `project_precommit_check` (see #963).
> GRDB compatiblity with Swift 6.0

- project.py
After the OS update we see certain projects fail with
```
panic: locale.c: 4486: Could not change LC_CTYPE locale to C.UTF-8, errno=9
```
This is because the perl binary seems to be not able to find the correct locale after the OS update. This PR rectifies that by setting the value accordingly when making a subprocess call to perl
> Set locale for perl binary after OS update

- sourcekit-xfails.json
Remove some now-passing cases, and add failures for swiftlang/swift#79636 + swiftlang/swift#57045
> Update stress tester XFAILs

- common.py
Remove `pipes` dependency as it is no longer part of the python standard library in the latest version. Replace with `shlex` module which is always available in python3.
> Remove python `pipes` module dependency

- projects.json
The fix has been merged but it's still not available in all nightly toolchains, so we should XFAIL until then.
> XFAIL package-distributed-system on Linux in 6.1 configuration

- projects.json
Adding SyndiKit.
* BSD
* MIT
* MPL 2.0
* CDDL
> Adding SyndiKit

- projects.json
This reverts commit 1690bc4e8e23fe17f4fe753a8354dde71e6e6ece, reversing changes made to 37d33ab2560f68ca78734638f77829a2d3cfee24.
The xfailed tests seem to have been fixed by
"Wrap SE-0481 into an upcoming feature until source incompatibilities are resolved"
https://github.com/swiftlang/swift/pull/82732.
> Revert "Merge pull request #1005 from xedin/rdar-152672172-xfails"

- sourcekit-xfails.json
Reverts swiftlang/swift-source-compat-suite#1016, updating for swiftlang/swift#84036 which actually happens to make this no longer too complex (although it still takes tens of seconds)
> Revert "Update stress tester XFAILs"

- projects.json
XFAIL the SwiftLint-Legacy project on debug and release till  rdar://159565344 and rdar://160182442 is addressed
> XFAIL SwiftLint-Legacy rdar://159565344 rdar://160182442
